### PR TITLE
Master - JS refactoring - Modify AdminGenericInterfaceMappingXSLT

### PR DESCRIPTION
**Pull request by s7design**
Hello @mrcbnsls ,

Hereby is refactored JS for AdminGenericInterfaceMappingXSLT module. Created new JS which binds event on 'Save and finish' button. Included Selenium test for this module which test module and JS.

Please let me know if you have any comments regarding this PR.

Regards,
Sanjin

### CODE REVIEW

**Comment by mrcbnsls** [comment]
Hi @zottto, I am currently having issues getting this module to work in my local system and am thus not able to test the changes. Maybe you could have a look and merge it if appropriate.

**Comment by zottto** [comment]
Hi Sanjin,

Selenium test ist failing for me with different errors:

1.  not ok 18 - Exception in Selenium': An element could not be located on the page using the given search parameters: #Operation,css selector at (eval 122) line 95.


2. Message: Need Name! E. g. True(\$A, 'Test Name')!

 Traceback (5436):
   Module: Kernel::System::UnitTest::True Line: 312
   Module: Kernel::System::UnitTest::__ANON__ Line: 160
   Module: (eval) Line: 134
   Module: Kernel::System::UnitTest::Selenium::RunTest Line: 133
   Module: (eval) Line: 190
   Module: Kernel::System::UnitTest::Run Line: 197
   Module: Kernel::System::Console::Command::Dev::UnitTest::Run::Run Line: 78
   Module: (eval) Line: 444
   Module: Kernel::System::Console::BaseCommand::Execute Line: 438
   Module: Kernel::System::Console::InterfaceConsole::Run Line: 86
   Module: bin/otrs.Console.pl Line: 38


 not ok 50 - ERROR: Need Name! E. g. True(\$A, 'Test Name')

 not ok 51 - Exception in Selenium': An element could not be located on the page using the given search parameters: //button[@id='MappingInboundConfigureButton'],xpath at (eval 122) line 166.


Please check again.

Thanks,
Marc

**Comment by s7design** [comment]
Hello @zottto ,

Checked test and added some WaitFor() that could arise issue you experienced. Additionally removed regex from True(), seems that is also creating issue.

Please if you could check it again with these changes and let me know the results.

Regards,
Sanjin

**Comment by zottto** [comment]
Still unit test errors:

 not ok 50 - JS redirection is successful to AdminGenericInterfaceOperationDefault screen
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};
Selenium command success: $VAR1 = {
  'args' => [],
  'command' => 'executeScript',
  'script' => 'return typeof($) === "function" && $("#MappingInboundConfigureButton").length',
  'session_id' => '4eea9ffa-a982-4c9c-96da-d41ccd08778f'
};

 not ok 51 - Exception in Selenium': An element could not be located on the page using the given search parameters: //button[@id='MappingInboundConfigureButton'],xpath at (eval 122) line 173.

Marc

**Comment by s7design** [comment]
Hi @zottto 

I tested it and it works fine for me. I also rebased this PR if the test work on test server which are tested by Travis. If you have idea what ids different on your system please let me know and I will try to fix it.
Could you please put fix sleep instead 
https://github.com/OTRS/otrs/pull/1223/files#diff-f6ad6d631760e3d56ec24989e75c40efR169

I think that the error messages  which you mentioned in the previous comment tell that there is a problem with waiting to load the button (MappingInboundConfigureButton).  

Regards
Zoran

**Comment by zottto** [comment]
What ever happened, the unit tests are now working for me.

Merged with 8e3e90b.

Thanks,
Marc

**Pull request closed without merging**
