### PR TITLE
Changed wording, as this option is still valid in newer versions of I…

### PR DESCRIPTION
**Pull request by MBRG**
…E (like 11).

### CODE REVIEW

**Comment by mgruner** [comment]
Hi @zottto. Can you please review this? If it is only relevant for IE8, it could also be removed, right?

**Comment by MBRG** [comment]
Hi, we tested this today on a system and with IE 11 and it did have an effect (a positive one). So we should not drop the option altogether.

**Comment by zottto** [comment]
Hi @MBRG, hi @mgruner,

the setting is relevant for all versions of IE, but we added it to our code as an replacement for the sandbox attribute, that is not supported by older IEs.
The sandbox attribute is supported starting IE10, so we could remove this special IE setting for OTRS 5 or at least for master.

What do you think?

Marc

**Comment by mgruner** [comment]
Hi Marc,

will SSO work in IE10+ then without the setting?

Martin Gruner
Team Lead R&D

OTRS AG
Bahnhofplatz 1a
94315 Straubing

T: +49 (0)6172 681988 0
F: +49 (0)9421 56818 18
I:  www.otrs.com/

Geschäftssitz: Bad Homburg, Amtsgericht: Bad Homburg, HRB 10751, USt-Nr.: DE256610065
Aufsichtsratsvorsitzender: Burchard Steinbild, Vorstand: André Mindermann (Vorsitzender), Christopher Kuhn, Sabine Riedel

Mobile Kommunikation und transparente Prozesse - Mit der OTRS Business Solution™ Managed 5 schnell und ohne eigene IT-Ressourcen starten  - Jetzt neue Features entdecken und bestellen
https://www.otrs.com/neu-in-otrs-business-solution-5-mobile-kommunikation-transparente-prozesse/?lang=de

**Comment by MBRG** [comment]
Hi,

this came up because on an OTRS 5 system and SAML SSO with IE11 was bringing up errors and was not showing the ticket zoom correctly. A "script disbled" message was shown instead of the ticket content. After changing this option, the content was shown correctly.

So in this setting, this option solved a problem on the system which would not be solvable otherwise with the current knowledge.

**Comment by zottto** [comment]
Hi @MBRG,

this option disables a IE-specific security setting that was introduced for older IEs that do not understand the general sandbox attributes on iframes.
Because IE10+ understand those sandbox attributes now, the IE-specific security setting is not needed anymore in these browsers.
We will remove the IE-security setting completely which also makes the sysconfig setting unnecessary.

**Comment by zottto** [comment]
Improved description for OTRS 5 (eebea78) and 4 (3cfed1f).

**Comment by zottto** [comment]
Removed config setting and IE-specific attribute completely for master (a5c173a).
Thanks for your help!

**Pull request closed without merging**
