### PR TITLE
Update AgentTicketProcess.pm

### PR DESCRIPTION
**Pull request by nilei**
New processes created with the typical Parent::Child syntax are displayed in a nice multi level dropdown. See attached image for an example.

Cheers, Nils

screen shot 2017-11-14 at 11 54 18

### CODE REVIEW

**Comment by mgruner** [comment]
Only for master, I guess?

**Comment by nilei** [comment]
Hi @mgruner, I usually only add PRs to master. Would you also add this to OTRS 6.0.2 ?

Cheers, Nils

**Comment by mrcbnsls** [comment]
Nice, merged to master for now. @mgruner, as it is such a small change: should we also take it to rel-6_0?

**Comment by mguarienti** [comment]
Hi @nilei 

I made the changes in the source file, and I created the processes with the Parent::Child nomenclature, but I didn't get any changes.. Would you give me more details of the configuration?

tanks

**Pull request closed without merging**
