### PR TITLE
Stats::Dynamic::TicketList: Add 'NumberOfArticles' ticket attribute.

### PR DESCRIPTION
**Pull request by eliasp**
This makes it possible to get the number of articles per Ticket in the TicketList stats module.

### CODE REVIEW

**Comment by mgruner** [comment]
Hi @eliasp! Thanks for this PR!

**Comment by mgruner** [comment]
@dominikklein can you please review this? Do you think it is correct? Should we merge to OTRS 5 or master?

**Comment by eliasp** [comment]
I've rebased the PR on current `master` and resolved the conflicts.

**Comment by dominikklein** [comment]
Hi Elias,
thanks a lot.

merged in master and also for OTRS 5.
I only changed the default value, because it is possible that tickets don't have a article.

Best regards,
Dominik

**Pull request closed without merging**
