### PR TITLE
[ Master - Bug 11132 ] - Loss of attached files with long Cyrillic names

### PR DESCRIPTION
**Pull request by s7design**
http://bugs.otrs.org/show_bug.cgi?id=11132

Hello @mgruner ,

Hereby is proposal for fixing bug #11132. Would like to elaborate on my research first. 

There is an issue with long Cyrillic attachment names (around, give or take, 99 characters) when using ArticleStorageFS. Linux limit for file names is 255 bytes. Cyrillic letter takes 2 bytes to encode. Having only file name of 99 chars in Cyrillic is fine, but when using ArticleStorageFS, files that are wrote by it goes over 255 bytes and Linux can't create them. E.g. $Filename.content-type , $Filename.content_alternative , ect. So the end result is that some files are created and some weren't. It gives false result in AgentTicketZoom, showing attachment but essentially without content.

With fix all attachment with name more then 100 character, are parsed to 80 chars. Now even with Cyrillic or some other characters that take 2 bytes and some different characters that takes 3 bytes to encode ArticleStorageFS will work.

Additionally while working on this bug, found out that attachment that have 2 characters extension were not working when parsed out, so added that as well.

If there are any question, issues regarding this PR or you want me to give more details around this problem please let me know.

Regards,
Sanjin

### CODE REVIEW

**Comment by carlosfrodriguez** [comment]
Hi @s7design,

Could you please cover this with UnitTests? be sure to include long names that differs after the character 80.

((enjoy))
cr

**Comment by s7design** [comment]
Hi @carlosfrodriguez ,

Updated PR with Unit Test. In test there are different cases with Latin, Cyrillic and Japanese characters length; representing 1, 2, 3 byte per character respectively when encoding and saving attachment in FS.

If you remove proposed fix in Main.pm to cut characters for long names, test will fail and show log error that it can't write file with long name.

Please let me know if there is anything else you need regarding this issue.

Regards,
Sanjin

**Comment by carlosfrodriguez** [comment]
Hi @s7design,

I have 2 topics around this PR.

1st I see that some lines above there is similar code with different values 95 instead of 70, should we also have to modify that value to 70? or both to 95?

2nd I run the unit test in Fedora20 and it constantly fails in 4 tests, for example
```
not ok 175 - FS ArticleAttachmentIndex() Attachment name Japanese 20 characters (
is        '人だけの会員制転職サ人だけの会員制転職サ.txt' 
should be '人だけの会員制転職サ人だけの会員制転職サ.txt'
)
```
Both strings are similar, so I think it should be a matter of utf-8 flags or so, could you check it?

there are no particular error messages, but just at the end
```
ERROR: OTRS-otrs.UnitTest-10 Perl: 5.18.2 OS: linux Time: Thu Dec  3 17:39:22 2015

 Message: Can't remove: /Users/Carlos/Dev/OTRS/otrs-5_0/var/article/2015/12/03/4: Directory not empty!

 Traceback (1270): 
   Module: Kernel::System::Ticket::ArticleStorageFS::_ArticleDeleteDirectory Line: 1149
   Module: Kernel::System::Ticket::ArticleStorageFS::ArticleDelete Line: 150
   Module: Kernel::System::Ticket::TicketDelete Line: 605
   Module: (eval) Line: 259
   Module: Kernel::System::UnitTest::Run Line: 179
   Module: Kernel::System::Console::Command::Dev::UnitTest::Run::Run Line: 72
   Module: (eval) Line: 436
   Module: Kernel::System::Console::BaseCommand::Execute Line: 430
   Module: Kernel::System::Console::InterfaceConsole::Run Line: 86
   Module: bin/otrs.Console.pl Line: 38
```

**Comment by s7design** [comment]
Hi @carlosfrodriguez ,

Updated Unit Test to have consistent test case for each type of character in attachment name. 

Considering your 2nd remark, currently there are some issues with our fedora machine so i am unable to conduct testing in that environment and check the issue you are experiencing. Will have to come back on it later on.

Regards,
Sanjin

**Comment by carlosfrodriguez** [comment]
Hi @s7design,

I tried again and it is still failing for Fedora :-(

.............................................................................................................................................................................. not ok 175 - FS ArticleAttachmentIndex() Attachment name Japanese 20 characters (is '人だけの会員制転職サ人だけの会員制転職サ.txt' should be '人だけの会員制転職サ人だけの会員制転職サ.txt')
................... not ok 195 - FS ArticleAttachmentIndex() Attachment name Japanese 75 characters (is '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会.txt' should be '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会.txt')
................... not ok 215 - FS ArticleAttachmentIndex() Attachment name Japanese 120 characters (is '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ.txt' should be '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ.txt')
................... not ok 235 - FS ArticleAttachmentIndex() Attachment name Japanese 140 characters (is '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ.txt' should be '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ.txt')
........

**Comment by s7design** [comment]
Hello @carlosfrodriguez ,

I revisited this problem and found out that Fedora have some generally known issues with encoding 3 byte characters. It require some additional mods to be installed in order to work with them.

Test crashes are not connected with our fix, since even test with '20' 3 bytes characters is failing on Fedora, which is case where our fix is not in play.  I modified test to escape test cases with 3 byte characters if distribution is Fedora.

Regards,
Sanjin

**Comment by carlosfrodriguez** [comment]
Hi @s7design,

Unfortunately I also have some issues with ubuntu 13010

+-------------------------------------------------------------------+
/Users/Carlos/Dev/OTRS/otrs-5_0/scripts/test/Ticket/ArticleStorageNameLenght.t:
+-------------------------------------------------------------------+
..............................................................................................................................................................................
 not ok 175 - FS ArticleAttachmentIndex() Attachment name Japanese 20 characters (is '人だけの会員制転職サ人だけの会員制転職サ.txt' should be '人だけの会員制転職サ人だけの会員制転職サ.txt')
...................
 not ok 195 - FS ArticleAttachmentIndex() Attachment name Japanese 75 characters (is '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会.txt' should be '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会.txt')
...................
 not ok 215 - FS ArticleAttachmentIndex() Attachment name Japanese 120 characters (is '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ.txt' should be '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ.txt')
...................
 not ok 235 - FS ArticleAttachmentIndex() Attachment name Japanese 140 characters (is '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ.txt' should be '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ.txt')
........
=====================================================================
 Product:     OTRS 5.0.x git
 Test Time:   2 s
 Time:        2016-04-08 17:17:21
 Host:        otrs.master.mandalore.com
 Perl:        5.14.2
 OS:          Linux
 Vendor:      ubuntu 13.10
 Database:    mysql 5.5.35
 TestOk:      239
 TestNotOk:   4
 FailedTests:
  /Users/Carlos/Dev/OTRS/otrs-5_0/scripts/test/Ticket/ArticleStorageNameLenght.t #175 - FS ArticleAttachmentIndex, 195 - FS ArticleAttachmentIndex, 215 - FS ArticleAttachmentIndex, 235 - FS ArticleAttachmentIndex
=====================================================================

I have the feeling that this solution is "evil".

((enjoy))
cr

**Comment by s7design** [comment]
Hi @carlosfrodriguez 

I rebased and updated the test, actually I removed test case with Japanese characters. I think that this bugfix is blocked because of problem with Japanese characters in some OS.  However, this fix solve issue with attached files with long Cyrillic names. The reporter told about this issue, and I think we can merge such version, and then we will be able to open another bug for Japanese characters if it is necessary. Actually, Japanese character is not Cyrillic, it is similar, but in this case with Fedora it is totally different.

I understand that in that case we did not solve all issues, but we solved the issues which reported report about. Please let me know what do you think about all of that.

Regards
Zoran

**Comment by carlosfrodriguez** [comment]
Hi @s7design 

I pull your pull request again (to be sure its clean) and test it again in Ubuntu1310 and it is still failing

```
..............................................................................................................................................................................
 not ok 175 - FS ArticleAttachmentIndex() Attachment name Japanese 20 characters (is '人だけの会員制転職サ人だけの会員制転職サ.txt' should be '人だけの会員制転職サ人だけの会員制転職サ.txt')
...................
 not ok 195 - FS ArticleAttachmentIndex() Attachment name Japanese 75 characters (is '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会.txt' should be '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会.txt')
...................
 not ok 215 - FS ArticleAttachmentIndex() Attachment name Japanese 120 characters (is '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ.txt' should be '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ.txt')
...................
 not ok 235 - FS ArticleAttachmentIndex() Attachment name Japanese 140 characters (is '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ.txt' should be '人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ人だけの会員制転職サ.txt')
........
=====================================================================
 Product:     OTRS 5.0.x git
 Test Time:   2 s
 Time:        2016-05-20 12:28:15
 Host:        otrs.master.mandalore.com
 Perl:        5.14.2
 OS:          Linux
 Vendor:      ubuntu 13.10
 Database:    mysql 5.5.35
 TestOk:      239
 TestNotOk:   4
 FailedTests:
  /Users/Carlos/Dev/OTRS/otrs-5_0/scripts/test/Ticket/ArticleStorageNameLenght.t #175 - FS ArticleAttachmentIndex, 195 - FS ArticleAttachmentIndex, 215 - FS ArticleAttachmentIndex, 235 - FS ArticleAttachmentIndex
=====================================================================
```

Can you check it again?

((enjoy))
cr

**Comment by s7design** [comment]
Thanks @carlosfrodriguez 

I updated this PR I hope it finally works now :)

Regards
Zoran

**Comment by s7design** [comment]
Hi @carlosfrodriguez 

I rebased this PR to make it up to date with the changes which have been happened in meantime.

Regards
Zoran

**Comment by carlosfrodriguez** [comment]
Hi @s7design 

Thank you for the update, the tests seams to work, however we also made another internal fix. we need to review and possibly combine both.

**Comment by carlosfrodriguez** [comment]
Hi @dvuckovic 

Would you please take a look into this one?

((enjoy))
cr

**Comment by s7design** [comment]
it is fixed with bugfix: 

https://bugs.otrs.org/show_bug.cgi?id=12371

**Pull request closed without merging**
