### PR TITLE
Dutch stopwords

### PR DESCRIPTION
**Pull request by xhoy**
Added dutch stopwords

### CODE REVIEW

**Comment by mgruner** [comment]
Hello @xhoy, very nice! I wonder though; there are quite a few longer words like Nederlands. Do you really think these have to be filtered?

**Comment by xhoy** [comment]
Dunno, but there is a Highfrequencie list in webselex for dutch, german and english, i just picked the first 300 of that list, so these are the 300 most common words in dutch (i guess?)

**Comment by xhoy** [comment]
Just some clarification, I thought that the stop words list would include words that would be EXCLUDED in the search results en thus clearing them for "the most common" words, like "the" and "is" for example.

My thought then was, these are words you would never search since they would only return crappy results. so I figured that the 300 "most common" words (but i have more if you like) would as well just return useless results since non of these words would be indexed at all and create a faster search engine.

**Comment by mgruner** [comment]
Thanks. Can I ask you to please sign our CLA as described at https://otrs.github.io please? I believe that I don't have a copy from you yet. Then I will proceed to merge your PR.
Best regards, Martin

**Comment by mgruner** [comment]
Merged, thanks! I reduced the list to about 150 words to be like the other lists.

**Pull request closed without merging**
