### PR TITLE
Modularize AgentTicketZoom

### PR DESCRIPTION
**Pull request by moritz**
Start to modularize AgentTicketZoom by putting the "Ticket Information" sidebar widget into a separate module, and a generic module loader for more sidebar widgets.

If this meets your approval, I'll also factor out the "Customer Information" and the "Linked Objects" widgets into separate modules.

### CODE REVIEW

**Comment by reneeb** [comment]
+1

**Comment by moritz** [comment]
FWIW the "Links" table cannot easily be ported to a module, because it emits output to either the sidebar or the main content area, depending on the `LinkObject::ViewMode` setting.

So one could leave it unported, or generalize the module system so that a module can return the column (main or sidebar), an integer or string used for ordering the output from the modules, and the actual output. That would have the additional advantage of being able to modularize the rest of AgentTicketZoom too, but add complexity.

Note that I'll be absent for most of August, so if you want the bigger solution (or improvements to the existing patches), it'll have to wait until September.

**Comment by moritz** [comment]
OK, I've implemented the bigger solution after all. Enjoy!

**Comment by thorsteneckel** [comment]
great work :+1:

**Comment by capeit-tto** [comment]
:+1: ...finally. I've been wondering how long this would be only in KIX4OTRS.

**Comment by moritz** [comment]
Hi @mgruner,

any news regarding this pull request? Is this a direction into which OTRS wants to move?

Cheers,
Moritz

**Comment by mgruner** [comment]
Hello @moritz and all. Thanks a lot for your effort so far. Yes, modularizing this is definitely a good idea. Can you please rebase the PR, as there seem to be some conflicts now? Regarding the link table, a simple solution would be to just register two module calls, one for the sidebar, and one for the main column. Then it could just decide which one to use. The ordering could be based on the numbering in SysConfig. I believe that would be simple and also consistent with other places in OTRS.
If we can agree on a solution and have the feature covered with Selenium tests, I'd love to merge this for OTRS 6.
Best regards, Martin

**Comment by moritz** [comment]
Hi @mgruner,

if I rebase it, will you please supply the Selenium tests and merge it soon afterwards? I have zero experience with Selenium and no suitable environment, and I don't want to rebase it several times while waiting for a merge.

Cheers,
Moritz

**Comment by mgruner** [comment]
Hi @moritz. This should be possible. Probably @s7design can supply Selenium tests for the widgets.

**Comment by s7design** [comment]
Hello @moritz and @mgruner ,

Yes, we will be able to provide Selenium tests for this. I will start working on this ASAP.

Regards,
Sanjin

**Comment by mgruner** [comment]
@s7design: please wait until I merged this. I'll ping you then.

**Comment by moritz** [comment]
My patch didn't change any behavior or appearance of AgentTicketZoom; so it would be fine to develop Selenium tests for master, and they should still pass with this brnach.

**Comment by s7design** [comment]
Hi all,

Thanks Martin, it is better idea, it will be easier for us if it is merged.

@moritz  fell free to ask us if you need something about Selenium testing in general. 
Here is our mail, but I can give you my Skype if it is necessary.

Regards
Zoran

**Comment by mgruner** [comment]
Hi @moritz,

we already have tests. They should be extended after your changes to check that the widgets can be toggled, for example.

Martin Gruner
Team Lead R&D

OTRS AG
Bahnhofplatz 1a
94315 Straubing

T: +49 (0)6172 681988 0
F: +49 (0)9421 56818 18
I:  www.otrs.com/

Geschäftssitz: Bad Homburg, Amtsgericht: Bad Homburg, HRB 10751, USt-Nr.: DE256610065
Aufsichtsratsvorsitzender: Burchard Steinbild, Vorstand: André Mindermann (Vorsitzender), Christopher Kuhn, Sabine Riedel

Mobile Kommunikation und transparente Prozesse - Mit der OTRS Business Solution™ Managed 5 schnell und ohne eigene IT-Ressourcen starten  - Jetzt neue Features entdecken und bestellen
https://www.otrs.com/neu-in-otrs-business-solution-5-mobile-kommunikation-transparente-prozesse/?lang=de

**Comment by mgruner** [comment]
We should also consider placing the module files in Kernel/Output/HTML to be consistent.

**Comment by mgruner** [comment]
@moritz, any news?

**Comment by moritz** [comment]
@mgruner I've re-done the work in a second branch based on current master, and opened #953 instead of this one.

**Comment by mgruner** [comment]
FYI: I just merged the successor #953.

**Comment by mgruner** [comment]
Thanks a lot to all, especially to @moritz!

**Pull request closed without merging**
