### PR TITLE
Rel-5_0 - OTRS - ProcessManagement - updated unit test - part 2

### PR DESCRIPTION
**Pull request by s7design**
Hello @mgruner ,

Here's updated part of unit tests for ProcessManagement/DB.

Regards,
Sanjin

### CODE REVIEW

**Comment by mgruner** [comment]
Hello Sanjin, I see errors on PostgreSQL. Please consult with Zoran about this.

**Comment by s7design** [comment]
Hi @mgruner 

The PR is updated, I tested it now, and all tests work in my system.
please let me know, if there are some errors.

Regards
Zoran

**Comment by s7design** [comment]
Hi @mgruner 

I saw that there were some errors in Travis in all environments. I rebased this PR because it seemed there is a problem with new configuration for OTRSCodePolice in Travis.

Regards
Zoran

**Comment by mgruner** [comment]
Merged, thank you! Sorry about the travis noise, I had some issues adding support for OTRSCodePolicy. But it should be green again soon in master/rel-5_0.

**Pull request closed without merging**
