### PR TITLE
OTRS version number removed from PDF properties, HTTP and e-mail headers

### PR DESCRIPTION
**Pull request by pboguslawski**
PDF files created by OTRS contain full OTRS version number in their
properties. Such information is presented also in HTTP and e-mail
headers if Secure::DisableBanner is not enabled (default).

Software version number should not be presented to third parties
if not necessary (enhanced security). This modification removes
OTRS version number from PDF files created using OTRS
(i.e. ticket PDF printouts), HTTP and e-mail headers.

Related: https://dev.ib.pl/ib/otrs/issues/28
Author-Change-Id: IB#1004612

### CODE REVIEW

**Comment by mgruner** [comment]
Please see 6b1844c16723984009aac6223e1d7cddf858ad0b.

**Comment by mgruner** [comment]
Please see also f1f4cd06cf30ee1618b8b15516013829751f6fd9.

**Comment by mgruner** [comment]
Hi Pawel,
thanks a lot for your proposal. I disagree about your requirement; usually MUAs embed their version information in emails. But in OTRS there is a config setting "Secure::DisableBanner" that actually hides all information about the software, not just the version number. I added support for that to HTTPHeaders.tt and PDF.pm to only show the info if Secure::DisableBanner is not active. Let me know if you see any issues there.
Best regards, Martin

**Comment by mgruner** [comment]
I also backported these commits BTW.

**Comment by pboguslawski** [comment]
Hi Martin,

Thank you for your comments.

> But in OTRS there is a config setting "Secure::DisableBanner"

Secure::DisableBanner is "all or nothing" switch. We prefer not to show any version details but still be able to advertise OTRS in headers.

> usually MUAs embed their version information in emails

We prefer tools that allow fine-tuning in this area so we've made even step further - please see

https://dev.ib.pl/ib/otrs/issues/29

If you'll like this mod - let us know - we'll try to create PR from our IB#1004615 branch.

Regards,
Pawel

**Pull request closed without merging**
