### PR TITLE
Added MailReprocessSpoolDir option

### PR DESCRIPTION
**Pull request by pboguslawski**
This mod introduces new SysConfig option MailReprocessSpoolDir
which allows one to change location of e-mail messages stored
for reprocessing.

Related: https://dev.ib.pl/ib/otrs/issues/54
Author-Change-Id: IB#1017361

### CODE REVIEW

**Comment by mgruner** [comment]
Hello @pboguslawski. Why would this be a requirement, what's a use case for this?

**Comment by pboguslawski** [comment]
Hi,

We use it to specify custom dir for spool. If Article & tmp dirs are configurable, why not spool?

Regards,
Pawel

**Comment by mgruner** [comment]
Ok, but what do you achieve with that? Article and tmp dirs can be quite big, but this one?

**Comment by pboguslawski** [comment]
Hi,

We don't like to keep dirs with changing data inside /opt/otrs directory and move stuff like articles, tmp, spool away from /opt/otrs. Using simlinks is less elegant than SysConfig parameter in our opinion that why this mod.

Regards,
Pawel

**Comment by carlosfrodriguez** [comment]
Hi @pboguslawski,

Thank you for your pull request, currently the backup.pl script does the backup for all var directory, with this feature this is not covered, can you add the manage of the spool directory into the backup.pl script? 

Please also rebase the this pull request
((enjoy))

**Comment by mgruner** [comment]
I'll close this pull request for now.

**Pull request closed without merging**
