### PR TITLE
Master - JS refactoring - AgentDashboardCustomerUserList

### PR DESCRIPTION
**Pull request by s7design**
Hello @zottto ,

Hereby is refactored AgentDashboardCustomerUserList.

Please let me know if you have any issues or questions regarding this PR.

Regards,
Sanjin

### CODE REVIEW

**Comment by zottto** [comment]
Hi Sanjin,

I think Core.Agent.CustomerInformationCenter.js is not the matching JS file for this code.
What about Core.Agent.Dashboard.js because it is a dashboard widget?

Marc

**Comment by s7design** [comment]
Hello @zottto ,

Thank you for follow up. This could be advocated both ways, since widget is shown in AgentCustomerInformationCenter screen, but you are right that it is dashboard widget. I will modify this PR and place JS functions accordingly in Core.Agent.Dashboard.js

Regards,
Sanjin

**Comment by s7design** [comment]
Hello @zottto ,

This PR is modified. Please let me know if you want me to sort out future merge conflicts that will arise now from Core.Agent.Dashboard.js

Regards,
Sanjin

**Comment by zottto** [comment]
Merged with c5cec99 (with slight changes).

Thanks,
Marc

**Pull request closed without merging**
