### PR TITLE
Master frontend usability - AdminSalutation

### PR DESCRIPTION
**Pull request by s7design**
Hello @zottto ,

Hereby are added BreadCrumb and form actions for AdminSalutation. Updated Selenium test accordingly to check for these additions.

Please let me know if you have any issues or questions regarding this PR.

Regards,
Sanjin

### CODE REVIEW

**Comment by s7design** [comment]
Hi @zottto 

This PR is updated in accordance with your suggestion.

Regards
Zoran

**Comment by zottto** [comment]
Hi Zoran / @s7design,

https://github.com/OTRS/otrs/pull/1411/files#diff-bcc0e27dbb22fc7153fc3bf0d87ab3c8R110

I think this old code is not necessary anymore, is it?

Marc

**Comment by s7design** [comment]
Hello @zottto ,

Thanks for feedback, you are right that is left from old code. PR is updated

Regards
Zoran

**Comment by zottto** [comment]
Merged with 1290f4e.

Thanks,
Marc

**Pull request closed without merging**
