### PR TITLE
Master - JS refactoring - AdminGenericInterfaceInvokerDefault

### PR DESCRIPTION
**Pull request by s7design**
Hello @zottto ,

Hereby is refactored AdminGenericInterfaceInvokerDefault JS.

Please let me know if you have any issues or questions regarding this PR.

Regards,
Sanjin

### CODE REVIEW

**Comment by zottto** [comment]
Hi Sanjin / @s7design,

the JS file does not match our coding standards (see OTRSCodePolicy checks), because the Init() function has more than one var statement.

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

I updated this PR. I removed insufficient "var" statements and also changed "for loop" with the "each" statement, it looks better in my opinion. Please check all of that because it is hard to test manually for me; we are not so familiar with this web-service features. 

Regards
Zoran

**Comment by zottto** [comment]
Hi Zoran / @s7design,

var statementsa within an inner function  must be kept, otherwise the variable is active in the outer scope. In this case that means, that the "var URL" must be defined within the event functions.

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

Thanks, I will rollback to the previous solution

Regards
Zoran

**Comment by s7design** [comment]
Hi @zottto 

I updated this PR as you suggested 

Regards
Zoran

**Comment by zottto** [comment]
Merged with b1ca2aa.

Thanks,
Marc

**Pull request closed without merging**
