### PR TITLE
[Rel-5_0 10117 ] - Filter in queue view for customer userID shows only customers from given backend

### PR DESCRIPTION
**Pull request by s7design**
http://bugs.otrs.org/show_bug.cgi?id=10117

Hi @mgruner 

We made again PR for the bug #10117. Now, we provided solution for  branch rel-5_0.  As you can see, we added new SysCongig item, which enable this type of search by unknow customers or doesn't.

There are typos in:
<pre> 
/opt/otrs/var/httpd/htdocs/js/Core.Agent.Dashboard.js:
   43                      Subaction: 'SearchCustomerID',
   44                      Term: Request.term,
   45:                     MaxResults: Core.Config.Get('CustomerAutocomplete.MaxResultsDisplayed')
   46                  };
   47  

/opt/otrs/var/httpd/htdocs/js/Core.Agent.TableFilters.js:
   50                      Subaction: 'SearchCustomerID',
   51                      Term: Request.term,
   52:                     MaxResults: Core.Config.Get('CustomerAutocomplete.MaxResultsDisplayed')
   53                  };
</pre>
because these param are set here:

<pre>
/opt/otrs/Kernel/Output/HTML/Templates/Standard/AgentDashboardTicketGeneric.tt:

  141: Core.Config.Set('CustomerIDAutocomplete.QueryDelay', "[% Data.queryDelay | html %]");
  142  Core.Config.Set('CustomerIDAutocomplete.MaxResultsDisplayed', "[% Data.maxResultsDisplayed | html %]");
  143  Core.Config.Set('CustomerIDAutocomplete.MinQueryLength', "[% Data.minQueryLength | html %]");

/opt/otrs/Kernel/Output/HTML/Templates/Standard/AgentTicketOverviewSmall.tt:

  147: Core.Config.Set('CustomerIDAutocomplete.QueryDelay', "[% Data.queryDelay | html %]");
  148  Core.Config.Set('CustomerIDAutocomplete.MaxResultsDisplayed', "[% Data.maxResultsDisplayed | html %]");

</pre>

There should be CustomerIDAutocomplete instead of CustomerAutocomplete. We fixed it also.

Please let me know if you have any suggestion.

Regards
Zoran

### CODE REVIEW

**Comment by s7design** [comment]
Hi @carlosgarciac ,

Added Selenium test TicketGenericFilter.t for TicketGeneric dashboard overview. We test filter when searching for tickets by customer that is not in DB.

Regards,
Sanjin

**Comment by carlosgarciac** [comment]
Hi @s7design,

While I was testing this fix Selenium test fails for me, I'm using Firefox, is strange but if I keep the window browser open test fails, if I keep the focus on the command line it works just fine, could you please help me reviewing this issue?


Best regards,
Carlos García

**Comment by s7design** [comment]
Hello @carlosgarciac ,

I managed to get crashes like you explained, indeed it is strange. Changed way of how sysconfig set through out frontend. I did multiple stress tests now without crashing.

Please if you could review it now, and let me know if it is still malfunctioning in your environment.

Regards,
Sanjin

**Comment by carlosgarciac** [comment]
Hi @s7design,

sorry for bother your with this topic, but 1 test is still failing on my system, even with a just created database and just SecureMode enabled in the ZZZAuto.pm file.

My environment description in case it is helpful:
Browser: Firefox 44.0
 Perl:        5.18.2
 OS:          MacOSX
 Database:    mysql 5.6.21
 TestOk:      72
 TestNotOk:   1

The error:
#56 - Test ticket with TN 2016012810000344 - not found on screen after filtering with customer - test1454009176742219840@first.com

Please let me know your comments.


Best regards,
Carlos García

**Comment by s7design** [comment]
Hello @carlosgarciac ,

Changed logic for WaitFor() on auto complete. This should now provide more stability in the test.

Please let me know if you are still experiencing crashes.

Regards,
Sanjin

**Comment by dvuckovic** [comment]
Hi @s7design,

we tried merging your fix, but an unrelated UT started failing (`AgentTicketCompose` in Selenium). Return format of the search results for existing customer user from the database was unexpected. We reverted for now, but do you have any ideas what's went wrong?

Thanks.

Regards,
Dusan

**Comment by s7design** [comment]
Hi @dvuckovic,

I rebased PR and updated AgentTicketCompose.t test. It worked for me without chnages, but I think it could be a problem if SendModule is not set correctly. 

It works in my system, we will see if there is a problem after Travis checking.

Regards
Zoran

**Comment by s7design** [comment]
Hi all,

I close this PR because it is merged in master and rel-5_0. It is commented on the bug report.  Ulrike Schneider suggested that it would be nice if there is fix for OTRS4. We are implementing this solution. If somebody has done that or it is not necessary in this moment please let me know.

Regards
Zoran

**Pull request closed without merging**
