### PR TITLE
Master frontend usability - AdminDynamicFieldCheckbox

### PR DESCRIPTION
**Pull request by s7design**
Hello @zottto ,

Hereby are added breadcrumbs and form action for AdminDynamicFieldCheckbox. In this PR included breadcrumb for AdminDynamicField as well (didn't want to create separate PR for such a small change). If this pose a problem, will modify this PR and create new one with AdminDynamicField breadcrumbs.

After we complete and merge breadcrumbs for other DynamicField types, will update Selenium test to check for these changes. At this moment test would fail since it goes through all object types in test. If breadcrumb label is inappropriate, will change it and update other DynamicField relevant PRs as well.

Please let me know if you have any issues or questions regarding this PR.

Regards,
Sanjin

### CODE REVIEW

**Comment by zottto** [comment]
Hi Sanjin / @s7design,

this works fine from the technical point of view, but has some problems with the translation of the breadcrumb text.
The text is translated word by word ("Ticket": "Change", "Checkbox", "Field") instead of "Change checkbox field") which leads to very strange translations in other languages (e.g. german, "Ticket: Ändern Kontrollkästchen Feld") and might be completely useless in other languages.

Please change the breadcrumb generation to translate the whole sentence ("Change checkbox field") to allow an individual translation here.

Please also check all other open PRs for this issue.

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

I fixed the problem that you mentioned above with translate breadcrumb item for subaction screen. I change also title for these screens

I am planing to update this PR and add notification as well. It will be done tomorrow. After that I will update other PRs for DF screens.

Reagrds
Zoran

**Comment by s7design** [comment]
Hi @zottto,

This PR is updated and hereby is added notification.

Regards
Zoran

**Comment by s7design** [comment]
Hi @zottto,

As you can see, I added notification for delete DF in this PR. In my opinion there is not neccesaary adding this part in other PRs for DFs.

I am planing to add test for all notifications and breadcrumbs when you merge these PRs. The test AdminDynamicField.t will be extended. 

Regards
Zoran

**Comment by s7design** [comment]
Hi @zottto 

I updated this PR, there are not any notification for DF.

Regards
Zoran

**Comment by zottto** [comment]
Merged with 6629e65.

Thanks,
Marc

**Pull request closed without merging**
