### PR TITLE
Master - JS refactoring - AgentTicketEmail

### PR DESCRIPTION
**Pull request by s7design**
Hi @zottto 

Hereby is updated AgentTicketEmail module. We moved all JS code from TT to the new JS file.

Regards
Zoran

### CODE REVIEW

**Comment by zottto** [comment]
Hi Zoran / @s7design,

instead of looping through the dynamic fields and pushing them to the fields array, you should use the concat() function of JavaScript.

To avoid multiple new variables you can also do this inline:
```[Element1, Element2, Element3].concat(AnotherArray);```

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

Thanks for this suggestion, we discussed abut the best solution her and I think it helps us a lot.
You will see there are more PR where we have used similar approach for the arrays

Regards
Zoran

**Comment by s7design** [comment]
Hi @zottto 

PR is updated in regard to your suggestion.

Regards
Zoran

**Comment by zottto** [comment]
Merged with 5f03db5.

Thanks,
Marc

**Pull request closed without merging**
