### PR TITLE
Added Translatable attribute for several strings

### PR DESCRIPTION
**Pull request by urbalazs**
To find all &lt;Description&gt; and &lt;Title&gt; tags, which have no Translatable="1" attribute, use the following command in a terminal:
<code>grep -Hn '&lt;Description\\|&lt;Title' Kernel/Config/Files/*.xml | grep -v 'Translatable'</code>

### CODE REVIEW

**Comment by urbalazs** [comment]
There are many empty &lt;Title&gt; and &lt;Description&gt; tags in the files. I think, it should be filled some values:
<pre><code>Kernel/Config/Files/Framework.xml:4510: &lt;Title&gt;&lt;/Title&gt;
Kernel/Config/Files/Framework.xml:4522: &lt;Title&gt;&lt;/Title&gt;
Kernel/Config/Files/Framework.xml:4565: &lt;Title&gt;&lt;/Title&gt;
Kernel/Config/Files/Framework.xml:4605: &lt;Title&gt;&lt;/Title&gt;
Kernel/Config/Files/Framework.xml:4663: &lt;Title&gt;&lt;/Title&gt;
Kernel/Config/Files/Framework.xml:4778: &lt;Title&gt;&lt;/Title&gt;
Kernel/Config/Files/Framework.xml:4891: &lt;Description&gt;&lt;/Description&gt;
Kernel/Config/Files/Framework.xml:4927: &lt;Description&gt;&lt;/Description&gt;
Kernel/Config/Files/Framework.xml:5375: &lt;Title&gt;&lt;/Title&gt;
Kernel/Config/Files/Ticket.xml:8202: &lt;Description&gt;&lt;/Description&gt;
Kernel/Config/Files/Ticket.xml:8503: &lt;Title&gt;&lt;/Title&gt;
Kernel/Config/Files/Ticket.xml:8532: &lt;Title&gt;&lt;/Title&gt;
Kernel/Config/Files/Ticket.xml:9574: &lt;Title&gt;&lt;/Title&gt;</code></pre>

These are not empty, but they contain a string, which seems to be a name of a Sysconfig or a module. I think it should be renamed to a more informative string:
<pre><code>Kernel/Config/Files/Framework.xml:5461: &lt;Description&gt;PublicDefault&lt;/Description&gt;
Kernel/Config/Files/Framework.xml:5462: &lt;Title&gt;PublicDefault&lt;/Title&gt;
Kernel/Config/Files/Framework.xml:5473: &lt;Description&gt;PublicRepository&lt;/Description&gt;
Kernel/Config/Files/Framework.xml:5474: &lt;Title&gt;PublicRepository&lt;/Title&gt;
Kernel/Config/Files/Framework.xml:5485: &lt;Description&gt;PublicSupportDataCollector&lt;/Description&gt;
Kernel/Config/Files/Framework.xml:5486: &lt;Title&gt;PublicSupportDataCollector&lt;/Title&gt;
Kernel/Config/Files/Ticket.xml:8421: &lt;Description&gt;AgentCustomerSearch&lt;/Description&gt;
Kernel/Config/Files/Ticket.xml:8422: &lt;Title&gt;AgentCustomerSearch&lt;/Title&gt;
Kernel/Config/Files/Ticket.xml:8433: &lt;Description&gt;AgentUserSearch&lt;/Description&gt;
Kernel/Config/Files/Ticket.xml:8434: &lt;Title&gt;AgentUserSearch&lt;/Title&gt;</code></pre>

And these are marked for translation, but I think they shouldn’t be translated, because they are column names from the database (Kernel/Config/Files/Ticket.xml at line 2387-2409):
<pre><code>&lt;Item Translatable=&quot;1&quot;&gt;TicketNumber&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;Age&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;Created&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;Closed&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;FirstLock&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;FirstResponse&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;State&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;Priority&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;Queue&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;Lock&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;Owner&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;UserFirstname&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;UserLastname&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;CustomerID&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;CustomerName&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;From&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;Subject&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;AccountedTime&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;ArticleTree&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;SolutionInMin&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;SolutionDiffInMin&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;FirstResponseInMin&lt;/Item&gt;
&lt;Item Translatable=&quot;1&quot;&gt;FirstResponseDiffInMin&lt;/Item&gt;</code></pre>

**Comment by mgruner** [comment]
Hello @urbalazs, thanks for your suggestion. I applied the "receipent" typo. For the other strings I believe that only those which are actually translated somewhere should be marked as translatable. I agree about the DB columns, but they are actually used currently (at least in the statistics AFAIR). Best regards, Martin

**Comment by urbalazs** [comment]
Hi @mgruner, there was one more mistake in my pull request: for the English stopwords there is "German" in the description.

**Comment by mgruner** [comment]
Fixed, thanks!

**Pull request closed without merging**
