### PR TITLE
Normalized HTML

### PR DESCRIPTION
**Pull request by thorsteneckel**
Hi @mrcbnsls

The PR for our discussion over here:
https://github.com/OTRS/otrs/commit/56e636d9be08bcf6c2b63a7af4885ab7307eff76#commitcomment-13945102

Thanks!

### CODE REVIEW

**Comment by mrcbnsls** [comment]
Merged in bf71706, thanks!

**Comment by rolfschmidt** [comment]
Hi @mrcbnsls ! Is there maybe a possibility for a cherry pick to otrs 5?

**Comment by mrcbnsls** [comment]
Sure thing, @rolfschmidt. Done in d20d9d4.

**Comment by rolfschmidt** [comment]
Thank you very much @mrcbnsls  :+1:

**Pull request closed without merging**
