### PR TITLE
Master changed dtl to tt

### PR DESCRIPTION
**Pull request by s7design**
Hi @mgruner ,

While we were working on some bug, we saw that there are some messages and comments with .dtl instead .tt files.
I felt free to fix that. They are small changes, only in CustomerHeader.tt I changed dtl with tt block. The both of them work, but in my opinion it is better with template toolkit.  
My intention was to improve UX with correct messages. If you agree with me, you can merge it.

Regards
Zoran

### CODE REVIEW

**Comment by s7design** [comment]
Hi @mgruner ,
Now I saw that I committed these changes  from another github users (s7web). Let me know if this is a problem, I can make new PR if it would be necessary. 

Regards
Zoran

**Comment by mgruner** [comment]
No changes in Kernel/Language/*.pm and i18n/* please, these are automatically generated.

**Comment by s7design** [comment]
Yes, I forgot this. I will change this soon.

Thanks
Zoran

**Comment by carlosfrodriguez** [comment]
Hi @s7design,

Thank you for your pull request, it was merged in https://github.com/OTRS/otrs/commit/ea5b39babcebe72c42b7614b66d8bbe80a92e2cb.

((enjoy))
cr

**Pull request closed without merging**
