### PR TITLE
Add UnitTest::Helper methods for starting and rolling back transactions

### PR DESCRIPTION
**Pull request by moritz**
this way, tests that do not need to interact with the outside can
easily discard their own test objects, and avoid polluting the DB.

### CODE REVIEW

**Comment by moritz** [comment]
I'm also happy to report that adding the BeginWork and Rollback to scripts/test/Ticket.t reduces the run time of that test for me from about 21s to 8s (mysql, InnoDB); probably because the DB engine isn't force to write anything to disk as long as the transaction is uncommitted.

**Comment by mgruner** [comment]
Hello @moritz. The HelperObject only lives within one unit tests at maximum and can therefore be used as a scope guard. We already have a constructor parameter ```RestoreSystemConfiguration``` that is used to save the ZZZAuto.pm before the test and to restore it afterwards, even after a die(). We should use the same approach with another parameter like ```RollbackDBChanges```, ok?

**Comment by moritz** [comment]
Yes, sounds fine.

**Comment by moritz** [comment]
@mgruner I've Added an option `RestoreDatabase` in my latest commit (making it a bit easier to remeber, since the existing option also starts with `Restore`).

**Comment by s7design** [comment]
Hi @moritz 

As I told you in email, it looks very nice. I believe it could improve testing and especially cleaning up after testing.
We are be able to update all Unit test when it will be merged, of course  in arrangement with @mgruner

:+1: 

Regards
Zoran

**Comment by mgruner** [comment]
Hi @moritz. Thanks a lot, I merged this in d94451c without the changes to the other unit tests. I first want to see what your UT servers report about this change. I'm afraid that some still use MyISAM and then I would not be sure what to do as we cannot rely on the UT servers to rollback the things everywhere.

**Comment by rolfschmidt** [comment]
looks really nice ++

**Comment by pboguslawski** [comment]
Hi,

DB transactions in unit testing may interfere with DB transactions used by OTRS in the future (which seem to be required to avoid races), i.e, after applying mod

https://github.com/OTRS/otrs/pull/1571

unit test for ticket creation fails on MySQL/InnoDB with error

    Transaction isolation level can't be changed while a transaction is in progress[...]

because of trying to create nested transaction for ticket number generation.

Consider not using transactions for UT or at least adding option for otrs.Console.pl to run UT without transactions.

Regards,
Paweł

**Pull request closed without merging**
