### PR TITLE
 Master - JS refactoring - AgentDashboardCommon

### PR DESCRIPTION
**Pull request by s7design**
Hello @zottto ,

Hereby is refactored AgentDashboardCommon JS. Please if you could review this PR asap, would be more then grateful, since this is closely connected with remaining of AgentDashboard widgets (AgentDashboardTicketGeneric.tt, AgentDashboardUserOnline.tt, ect. ). Refactoring of all those widgets in one PR would be a bit overwhelming so decided to take this approach. Will continue working on, once we have this PR merged.

If you have any questions or issues regarding this PR, do not hesitate to ask. Looking forward to your feedback.

Regards,
Sanjin

### CODE REVIEW

**Comment by zottto** [comment]
Hi Sanjin,

1. Opening preferences is not working anymore in the dashboard. After clicking the pref link, the widget closes and opens again with the default view instead of the preferences page.

2. Naming variables: It's ok to name a variable %JSData, but an additional @JSDatas is really not nice. Please name the vars in a better readable way.

3. Function naming in JS: If functions initialize something (e.g. events), it is helpful to name them InitSomething() to better describe what they are doing. So ContentPreferences is no good name and should better be something like InitWidgetPreferences etc.

Thanks,
Marc

**Comment by s7design** [comment]
Hello @zottto ,

Thank you for feedback regarding variable names. Corrected in following commit naming, please if you could check it.

Considering behaviour you are experiencing for dashboard widget preference window, I am not sure what is wrong there. Just did triple check of each dashboard widget and everything perform as expected in my environment. Please if you could test it again, perhaps there are some issues with cache or something else. If you are still encountering same issue, I will then investigate more deeply.

Looking forward to your answer.

Regards,
Sanjin

**Comment by zottto** [comment]
Still see the issue: prferences show up for a short moment and are closed again immediately (Browser Chrome). The function UserOnlineRefresh has still an old name (without "Init").

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

I couldn't reproduce such issue. I know that it sounds strange, but it works fine for me.
I rebased this PR and renamed function UserOnlineRefresh to InitUserOnlineRefresh.

Please let me know if you have idea how I can reproduce this and fix it after that.

Regards
Zoran

**Comment by zottto** [comment]
I was able to find out, what the problem was - it was my cache. :-) Now everything is working fine for me.

Only one last thing: you often name variables Data, if you get some config values. Please give them more speaking names...

Thanks,
Marc

**Comment by zottto** [comment]
Hi Sanjin / @s7design,
can you please fix this last mentioned issue. That would be great, so that I could merge this PR soon.

Thanks,
Marc

**Comment by s7design** [comment]
Hello @zottto ,

Thank you for mentioning this. It totally slipped my mind to correct those variable names. Please check PR now after update.

Regards,
Sanjin

**Comment by zottto** [comment]
Merged with 182d6d5c923b7302a522d6c845a721452ea1d7d2.

@s7design: Please update and rebase all pull requests, that are based on these changes.

Thanks,
Marc

**Pull request closed without merging**
