### PR TITLE
Master frontend usability - AdminCustomerUser

### PR DESCRIPTION
**Pull request by s7design**
Hi @zottto

Hereby is refactored AdminCustomerUser. Breadcrumb and 'Save and finish' button are added and Selenium test is modified in accordance with changes.
Please let me know if you have any comments on this PR.

Regards
Zoran

### CODE REVIEW

**Comment by zottto** [comment]
Merged with fffa385.

Thanks,
Marc

**Comment by zottto** [comment]
Hi Zoran / @s7design,

I accidentally merged this already, but I saw that also here a notification is removed.

Can you please update this?

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

Yes I can, it will be done very soon

Regards
Zoran

**Comment by s7design** [comment]
Hi @zottto 

This PR is updated. Hereby is added notification for update customer user. There has already  been notification for add customer user. The test AdminCustomerUser is extended with test cases where are tested are there notifications on the create after add and update entities.

Regards
Zoran

**Comment by zottto** [comment]
Merged with 33aa266.

Thanks,
Marc

**Pull request closed without merging**
