### PR TITLE
Fixed: Reply-To overwrites name from customer backend in <OTRS_CUSTOM…

### PR DESCRIPTION
**Pull request by Georgeto**
…ER_REALNAME> template replacement.

This bug was introduced in the fix for bug#4640.

### CODE REVIEW

**Comment by mgruner** [comment]
Hello @s7design, can you please review this?

**Comment by zilibasic** [comment]
Hi Georgeto,

Thanks for PR, after QA we merged it here:
https://github.com/OTRS/otrs/commit/0d78a83a2807e6a943e3cc3ebc63e1c0af6a8f7b

There is also extended test case. Please check it and let me know if you have any other suggestion.

Regards
Zoran

**Comment by zilibasic** [comment]
It will be available form OTRS 6.0.20 and OTRS 7.0.9.

Regards
Zoran

**Comment by Georgeto** [comment]
That went pretty fast, thank you!

**Pull request closed without merging**
