### PR TITLE
[Rel-5_0 Bug 9731] - Reply screen uses only email instead of full customer details 

### PR DESCRIPTION
**Pull request by s7design**
http://bugs.otrs.org/show_bug.cgi?id=9731

Hello @mgruner , @carlosfrodriguez

Hereby is proposed solution for fixing this issue. On ticket reply fields 'To' and 'Cc' will now use full customer details when available. For cases when there are no customer details regular behaviour remains.

Please let me know what do you think about this solution.

Regards,
Sanjin

### CODE REVIEW

**Comment by mrcbnsls** [comment]
Hi @s7design,

I think I like the way you do it now, but it differs from what is displayed when you manually add a recipient in AgentTicketCompose.

Your way: "Firstname Lastname" <mailaddress>
Adding manually: Firstname Lastname mailaddress

I think this should be consistent. Could you please see if it can be harmonized? Also, I'd like to see this covered by a selenium UT :-)

**Comment by s7design** [comment]
Hello @mrcbnsls ,

Updated Selenium test as you suggested. Test case is to input same customer with autocomplete click and to click on modal dialog for duplicated entry.

Please let me know if there are further changes required on this test.

Regards,
Sanjin

**Comment by mrcbnsls** [comment]
Hi @s7design,

Sorry for having this untouched for so long. Could you please update the PR and solve the merge conflicts? Thanks!

Marc

**Comment by s7design** [comment]
Hi @mrcbnsls 

I updated and rebased this PR, I hope it is good now.

Regards
Zoran

**Comment by mrcbnsls** [comment]
The broken behavior from the bug report is still the same for me. Can you please check again with the description from Carlos in the report if this is working for you?

**Comment by s7design** [comment]
Hi @mrcbnsls 

I tested it again now. It works for me, the test AgentTicketCompose.t also has such test case and it works fine.

bug_9731

In the picture is case when for TO is tried adding the same customer once more.

I use the description from Carlos in the report:

1. create ticket with the customer user from the DB
2. go to ticket zoom
3. create reply
4. in To field is customer user from the crated ticket
5. try to add this custumer user again
6. error dialog is shown ( `This address already exists on the address list. It is going to be deleted from the field, please try again.` )

Please let me know if you have any other behavior or I should change my test case.

Regards
Zoran

**Comment by mrcbnsls** [comment]
I just tested it again and it's not working for me. The behavior is still wrong and exactly how Carlos described it in the bug entry:

(1) This is how my test customer looks in the database:

database

(2) I created a ticket with this customer and open AgentTicketCompose. This is how it looks like (note that firstname and lastname are not displayed):

reply

(3) I search for this customer using the autocomplete:

autocomplete

(4) After I select him, no error message pops up (and the entry looks different from the existing one):

selected

(5) As a result, also the UT is still failing for me when it tries to accept the expected modal dialog:

````
 not ok 58 - Exception in Selenium': Error while executing command: clickElement: An element command could not be completed because the element is not visible on the page.: Element is not currently visible and so may not be interacted with
````

Can you please check again?

**Comment by s7design** [comment]
Hi @mrcbnsls 

I found the problem. You supose you create the ticket when you click on the link after creating customer user. 

`
Customer test added ( New phone ticket - New email ticket )!`
In that case there are a problem that you mentioned. I will try to fix that.

Regarding to UT, it works fine for me:

```
+-------------------------------------------------------------------+
/opt/otrs/scripts/test/Selenium/Agent/AgentTicketCompose.t:
+-------------------------------------------------------------------+
...................................................................................................
=====================================================================
 Product:     OTRS 5.0.x git
 Test Time:   28 s
 Time:        2016-09-26 14:03:04
 Host:        localhost
 Perl:        5.14.2
 OS:          Linux
 Vendor:      ubuntu 12.04
 Database:    postgresql 9.1.20
 TestOk:      99
 TestNotOk:   0
=====================================================================
```

Regards
Zoran

**Comment by mrcbnsls** [comment]
Hi Zoran,

Actually I am not using the way you described when testing it (using the "create ticket" link after creating a new customer), but I found the cause why the test is failing for me and the behavior is still the same. Please try adding

````
$Self->{'CheckMXRecord'} =  0;
````

to your configuration and run the test again. It seems the behavior is different due to this setting, although I currently don't understand why it has any influence. Could you please check it?

Marc

**Comment by s7design** [comment]
Hi @mrcbnsls 

Thanks Marc,
I will check that also, and then I will inform how it work on my system. It is so small issue but make a lot of problems :)

Regards
Zoran

**Comment by s7design** [comment]
Hi @mrcbnsls 

I tested it once more, but my behavior is obviously different then yours one. I disabled  CheckMXRecord but the customer user field is field in as expected ( "Firstname Lastname" <mailaddress> )

You can see in the picture. I know that this picture doesn't solve the problem. I will continue to find how I can reproduce your behavior. 

bug_9731


Regards
Zoran

**Comment by s7design** [comment]
Hi @mrcbnsls 

PR is rebased and little modified.

Regards,
Milan

**Comment by s7design** [comment]
Hello,

This bug has been fixed. Closing this PR.

Regards,
Sanjin

**Pull request closed without merging**
