### PR TITLE
Add support for SOAP requests with chunked Transfer-Encoding

### PR DESCRIPTION
**Pull request by fredericve**
This is based on the SOAP module that is already available in Kernel/cpan-lib/SOAP/Transport/HTTP.pm (on which the Transport::HTTP::SOAP module seems to be heavily based)

### CODE REVIEW

**Comment by mgruner** [comment]
Hi @fredericve! Thanks a lot for your proposal. Can I ask you to please sign our CLA as described on https://otrs.github.io?

**Comment by fredericve** [comment]
Hello @mgruner ,

The signed CLA was just sent to the appropriate address. You should be receiving it shortly.

**Comment by mgruner** [comment]
Yes, thank you very much!

Am 28.05.15 um 17:03 schrieb fredericve:
> Hello @mgruner <https://github.com/mgruner> ,
> 
> The signed CLA was just sent to the appropriate address. You should be
> receiving it shortly.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OTRS/otrs/pull/584#issuecomment-106383446>.
> 

-- 
Martin Gruner
Senior Developer R&D

OTRS AG
Bahnhofplatz 1a
94315 Straubing

T: +49 (0)6172 681988 0
F: +49 (0)9421 56818 18
I:  www.otrs.com/

Geschäftssitz: Bad Homburg, Amtsgericht: Bad Homburg, HRB 10751,
USt-Nr.: DE256610065
Aufsichtsratsvorsitzender: Burchard Steinbild, Vorstand: André
Mindermann (Vorsitzender), Christopher Kuhn, Sabine Riedel

Grenzenlose Kommunikation mit der OTRS Business Solution™! Bereichern
Sie Ihren IT Support und Kundenservice mit smarten Business Features!
https://www.otrs.com/solutions/otrs-business-solution-on-premise/?lang=de/#OTRS-Business-Solution-Basic-Features

**Comment by mgruner** [comment]
@carlosfrodriguez could you review this please?

**Comment by carlosfrodriguez** [comment]
Hi @fredericve 

Thanks for your pull request, I marge it in https://github.com/OTRS/otrs/commit/189067b67703f164f766df4ca261ef561d6a8ffe, with very small changes.

((enjoy))
cr

**Pull request closed without merging**
