### PR TITLE
integrate EnhancedPostmasterFilter from OPAR

### PR DESCRIPTION
**Pull request by reneeb**
Use the power of newer perl versions ;-)

### CODE REVIEW

**Comment by thorsteneckel** [comment]
pretty! :+1:

**Comment by mgruner** [comment]
Very nice. Can you please extend the unit tests to cover this feature? Then I will merge it for OTRS 6.

**Comment by reneeb** [comment]
Sure, I will add unittests...

**Comment by nilei** [comment]
Hi @reneeb, could you please add the unit tests? I would really love to see this implemented in OTRS 6.

;-)

-- Cheers, Nils

**Comment by reneeb** [comment]
Use #980 instead...

**Pull request closed without merging**
