### PR TITLE
[Rel-5_0 Bug 9950] - Ticket Split takes uses system address as the customer

### PR DESCRIPTION
**Pull request by s7design**
http://bugs.otrs.org/show_bug.cgi?id=9950

Hello,

Hereby is our proposal for fixing this issue. Next to already existing queue check, added to check if system address is in Article{From} parameter when Article{To} is not a Queue.

Created Selenium test to simulate three different split article cases covering different scenarios. 

Please let me know if there are any questions or issue regarding this PR. 

Regards,
Sanjin

### CODE REVIEW

**Comment by carlosgarciac** [comment]
Hi @s7design,

I did testing following steps on the bug report, 1st comment, and the problem is still there, I will talk with my colleges for an agreement about how this split feature should work on this part, then I will back to your with more info.

Best regards,
Carlos García

**Comment by carlosgarciac** [comment]
Hi @s7design,

After talking with @mgruner about this issue we agree (talking about article) that addressees in To or From  should be included depend on the case, and we could include the address from the customer as well.
I did some changes, on AgentTicketPhone that could be great if you can take a look on it and test it, if it is OK for you could you please extend the Selenium test please?

'diff --git a/Kernel/Modules/AgentTicketPhone.pm b/Kernel/Modules/AgentTicketPhone.pm
index 8f88572..85762a3 100644
--- a/Kernel/Modules/AgentTicketPhone.pm
+++ b/Kernel/Modules/AgentTicketPhone.pm
@@ -300,10 +300,13 @@ sub Run {
             );
 
             # save article from for addresses list
-            $ArticleFrom = $Article{From};
+            # just in case we have an article from customer
+            if ( $Article{SenderType} eq 'customer' ) {
+                $ArticleFrom = $Article{From};
+            }
 
             # if To is present and is no a queue
-            # set To as article from
+            # add To as article from
             if ( IsStringWithData( $Article{To} ) ) {
                 my %Queues = $QueueObject->QueueList();
 
@@ -315,9 +318,11 @@ sub Run {
                 }
 
                 my %QueueLookup = reverse %Queues;
+
                 if ( !defined $QueueLookup{ $Article{To} } ) {
-                    $ArticleFrom = $Article{To};
+                    $ArticleFrom .= ', ' . $Article{To};
                 }
+
             }
 
             # body preparation for plain text processing
@@ -352,7 +357,9 @@ sub Run {
                 my %CustomerUserList = $CustomerUserObject->CustomerSearch(
                     UserLogin => $Article{CustomerUserID},
                 );
+
                 for my $KeyCustomerUserList ( sort keys %CustomerUserList ) {
+                    $ArticleFrom .= ', ' . $CustomerUserList{$KeyCustomerUserList};
                     $Article{From} = $CustomerUserList{$KeyCustomerUserList};
                 }
             }
@@ -368,6 +375,7 @@ sub Run {
             );
         }
 
+        EMAILADDRESS:
         for my $Email ( Mail::Address->parse($ArticleFrom) ) {
 
             my $CountAux         = $CountFrom;
@@ -384,9 +392,14 @@ sub Run {
             }
 
             # check for duplicated entries
-            if ( defined $AddressesList{$Email} && $CustomerError eq '' ) {
+            if ( defined $AddressesList{$EmailAddress} && $CustomerError eq '' ) {
                 $CustomerErrorMsg = 'IsDuplicatedServerErrorMsg';
                 $CustomerError    = 'ServerError';
+
+                # next if split ticket
+                if ( $Self->{TicketID} && $Article{ArticleID} ) {
+                    next EMAILADDRESS;
+                }
             }
 
             if ( $CustomerError ne '' ) {'


Please let me know your comments.

Best regards,
Carlos García

**Comment by s7design** [comment]
Hi Carlos,

We tested it again and I rebased this PR. I tried to omit our changes in AgentTicketPhone, but as you can see in the first commit after rebase  there was error in Travis  
https://travis-ci.org/OTRS/otrs/builds/111958941. 

Actually our changes is necessary because of test case  which there is in the AgentTicketSplit.t test (the third one):

```
            {
                ArticleID      => $ArticleIDs[2],
                ToValueOnSplit => 'fromcustomer@example.com',
                ResultMessage  => 'From is Customer, To is Customer'
            },
```

Nicole mentioned something like that in the bug report. 

There is necessary to change $ArticleFrom only if there is appropriate address in  $QueueLookup{ $Article{To} and $SystemAddressLookup{$SystemAddressEmail}, 

```
                if ( !defined $QueueLookup{ $Article{To} } && defined $SystemAddressLookup{$SystemAddressEmail} ) {
                    $ArticleFrom = $Article{To};
                }

```

However, if there are regular mail addresses like in the case ( fromcustomer@example.com and tocustomer@example.com )  $ArticleFrom is not changed, it will stay  $Article{From} as there is before if statement.

https://github.com/OTRS/otrs/blob/master/Kernel/Modules/AgentTicketPhone.pm#L304
```
            # save article from for addresses list
            $ArticleFrom = $Article{From};
```

If you see some other test cases please let me know an we will be able to extend the test.

Regards
Zoran

**Comment by s7design** [comment]
This is fixed in https://github.com/OTRS/otrs/commit/fd6b99f9bb7cedcadd005a46e3990fa17d049938

Zoran

**Pull request closed without merging**
