### PR TITLE
fix bug 12286

### PR DESCRIPTION
**Pull request by xhoy**
Fix for [bug#12286](http://bugs.otrs.org/show_bug.cgi?id=12286)

### CODE REVIEW

**Comment by carlosfrodriguez** [comment]
Hi @xhoy 

Thank you for your pull request, Since '>' is normally not an issue and to do not change the current behavior, I modify your pull request to match for ']]>' instead. Additionally I remove some special characters.

The relevant commit for this is https://github.com/OTRS/otrs/commit/926b6da5ea84c64ec22949b30859962e67c30e70

((enjoy))
cr

**Comment by mgruner** [comment]
Hi Carlos,

I’m not sure about this. If we do XML quoting, we should do it consistently, escaping > and not ]]>, don’t you think?

Martin Gruner
Team Lead R&D

OTRS AG
Bahnhofplatz 1a
94315 Straubing

T: +49 (0)6172 681988 0
F: +49 (0)9421 56818 18
I:  www.otrs.com/

Geschäftssitz: Bad Homburg, Amtsgericht: Bad Homburg, HRB 10751, USt-Nr.: DE256610065
Aufsichtsratsvorsitzender: Burchard Steinbild, Vorstand: André Mindermann (Vorsitzender), Christopher Kuhn, Sabine Riedel

OTRS 5s – Modernste Technologie und höchste Sicherheit – die neuen Features für OTRS Free, OTRS Business Solution™ und OTRS Business Solution™ Managed! Erscheinungsdatum 01. November.
Jetzt entdecken! https://www.otrs.com/otrs-5s/?lang=de&utm_id=569

**Comment by mgruner** [comment]
I had to revert this, please see the bug for details.

**Comment by xhoy** [comment]
@mgruner Thank you but i think there is a mis understanding.  @carlosfrodriguez  fixed the bug, seperatly in commit 926b6da . He named (and thanked me) but he did the hard work not me :)

So its not "really" related to this commit and already part of the OTRS code base afaik?

So this could be closed?

**Comment by mgruner** [comment]
I had to revert this commit because of issues with a unit test. It must be checked and applied with modifications again.

**Comment by mgruner** [comment]
But you are right, this PR is not affected any more, I'll close it therefore.

**Pull request closed without merging**
