### PR TITLE
Translatable out of office message

### PR DESCRIPTION
**Pull request by pboguslawski**
Out of office strings in user name like

   User Name *** out of office till YYYY-D-M/2d ***

should be translatable not hardcoded english string.

Related: https://dev.ib.pl/ib/otrs/issues/24
Author-Change-Id: IB#1004603

### CODE REVIEW

**Comment by urbalazs** [comment]
I have a pull request for the same problem: https://github.com/OTRS/otrs/pull/1034
It shouldn't split the translatable string into substrings, because translators can not be able to understand the meaning of the string, if those are in separated messages. For example this one:

<pre>'*** ' . $LanguageObject->Translate('out of office till') . " $TillDate ($Till " . $LanguageObject->Translate('days') . ') ***';</pre>

Results 2 strings for translators:
out of office till
day

My solution:
<pre>$Kernel::OM->Get('Kernel::Language')->Translate('*** out of office till %s (%s day) ***', $TillDate, $Till);</pre>

Results only one string for translators:
*** out of office till %s (%s day) ***

**Comment by pboguslawski** [comment]
@urbalazs: Thanks for the hint. We've fixed it in cb8834d and added correct date formatting and small optimization.

**Comment by mgruner** [comment]
Hello @pboguslawski and @urbalazs. Thanks for your suggestions so far! There's one thing I don't understand about this PR. How do you determine the user's language? Usually we use the LanguageObject inside of the LayoutObject, which we cannot do in User.pm (backend). In this case I'd assume that always the default language would be used, which would defeat the purpose of this PR. Besides that, GetUserData will perform caching, so if the data is requested from another user, it might get returned with the wrong language for the out of office string...

I'll close this PR for now. Feel free to provide more information and a PR which solves the mentioned issues. I'm not sure if this can be solved with the current (bad) architecture of the out of office messages...

**Comment by pboguslawski** [comment]
Hello,

Thank you for pointing problem with using LanguageObject in User.pm.

Please see workaround to allow one to customize out of office message without using LanguageObject: https://github.com/OTRS/otrs/pull/1079

Regards,
Pawel

**Pull request closed without merging**
