### PR TITLE
Added generic redirect module to redirect agents to external URLs with optional ticket parameters

### PR DESCRIPTION
**Pull request by nilei**
Added generic redirect module to redirect agents to external URLs with optional ticket parameters.

This is very useful if you want to redirect your agents to other pages including OTRS internal parameters. The very typical use case is to open another ticket system and providing the OTRS ticket number in the URL.

-- Cheers, Nils

### CODE REVIEW

**Comment by mrcbnsls** [comment]
Sorry @nilei, I'm afraid I don't understand this PR. Whats the use case of this module? Are you sure you didn't forget anything? This looks incomplete to me. Currently I can't see the different between this module and just a fixed link. Where do you put the parameters you mentioned? Please pardon me if I'm missing something.

**Comment by nilei** [comment]
Hi @mrcbnsls, the module is very useful if you want to connect to other system without complex web service or other things. You could simply add a new ticket action which redirects you to the external app including some parameters in the URL. It is actually very similar to a fixed link, but configurable for OTRS administrators without modifying any template files which would be overwritten on each patch level update. It is a configurable and duplicatable ticket action that does nothing but redirecting. In some enhanced version I could think of an counter how often the redirect was used or any other additional module layer to modify the taget URL during runtime. We have a customer who requested this module already. They wanted to connect to a CRM System updating a record with time units (see internal finance 1599). What would you think is missing? -- Cheers, Nils

**Comment by jensoliver** [comment]
I also think it might be useful. Nils can you show an example how to add values of the ticket in the link. Also it should be possible to define if the link will open a new Tab or window.

**Comment by nilei** [comment]
Dear both, 

many thanks for your feedback!

I have added a lot of description to the XML config item. I think that not only ease the use and configuration but also explains the idea of the module.

-- Cheers, Nils

**Comment by mrcbnsls** [comment]
@mgruner, I think we should discuss this once you're back.

**Comment by nilei** [comment]
Similar approach: http://otrsaddons.com/content/externalurljump

**Comment by mgruner** [comment]
Hi @nilei, hi @jensoliver. In general it would be nice to have something configurable to allow the inclusion of external URLs into the menu. But having a Redirect module which does nothing but redirect seems to be rather useless, or did I miss something?

**Comment by mgruner** [comment]
You might want to adapt the solution in https://github.com/OTRS/otrs/pull/502 (I will close this one as it is for 3.3).

**Comment by nilei** [comment]
Hi @mgruner. 

The main idea is not just redirecting the user, but redirecting the user with having ticket parameters in the URL. Example use case would, if users wants to open en external system that stores some ticket data and search for all records belonging to the current ticket queue. Alternatively, the redirect my result into another web system to create a record and pre-fill some forms with current ticket data. 

I believe this a great enhancement and will support lots of integration scenarios where a full fletched SOAP/REST web service is just over-kill :-)

-- Cheers, Nils

**Comment by mgruner** [comment]
Ok, but for that you could just use an external link and interpolate
some ticket data via TT, like it is done in the PR I mentioned. Still no
need for a redirect module, or do I miss something?

Regards, mg

Am 27.03.15 um 00:17 schrieb nilei:
> Hi @mgruner <https://github.com/mgruner>.
> 
> The main idea is not just redirecting the user, but redirecting the user
> with having ticket parameters in the URL. Example use case would, if
> users wants to open en external system that stores some ticket data and
> search for all records belonging to the current ticket queue.
> Alternatively, the redirect my result into another web system to create
> a record and pre-fill some forms with current ticket data.
> 
> I believe this a great enhancement and will support lots of integration
> scenarios where a full fletched SOAP/REST web service is just over-kill :-)
> 
> -- Cheers, Nils
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OTRS/otrs/pull/392#issuecomment-86750878>.
> 

-- 
Martin Gruner
Senior Developer R&D

OTRS AG
Bahnhofplatz 1a
94315 Straubing

T: +49 (0)6172 681988 0
F: +49 (0)9421 56818 18
I:  www.otrs.com/

Geschäftssitz: Bad Homburg, Amtsgericht: Bad Homburg, HRB 10751,
USt-Nr.: DE256610065
Aufsichtsratsvorsitzender: Burchard Steinbild, Vorstand: André
Mindermann (Vorsitzender), Christopher Kuhn, Sabine Riedel

Schlanker, schneller und flacher denn je - OTRS 4! Und für alle, die
MEHR wollen: Entdecken Sie hier die OTRS Business Solution™ mit mehr
Business Features!
https://www.otrs.com/otrs-business-solution-fuer-besseren-kundenservice/?lang=de

**Comment by mgruner** [comment]
I'll close this PR for now. Please feel free to open a new one once you have new information!

**Comment by nilei** [comment]
@mgruner, maybe this is a stupid question, but could you show me an example how to configure an external link with TT on a ticket menu action item? Use Case: Show a new actin item "My Tool" and redirect the user to "http://mytool.example.com/search?q=$TicketNumber" where $TicketNumber is a placeholder for - guess what - the OTRS ticket number :-)

TIA
-- Cheers, Nils

**Pull request closed without merging**
