### PR TITLE
Readd the small generic interface log read tool

### PR DESCRIPTION
**Pull request by rolfschmidt**
Hi guys,
ich would like to ask you to readd the following missing console command to **rel-5_0** and **master**.
In our opinion it is a nice small tool for debug sessions at the customer. Maybe also some of your generic interface experts like @sb-otrs also already missing this simple tool. I used the old version of OTRS 4 to create this console command for you.

Best regards,
Rolf :-)

### CODE REVIEW

**Comment by mgruner** [comment]
Merged with slight changes in e21b0f0240b331d6b3f8c3a80c5e7f49605bda73 and backported, thanks a lot @rolfschmidt! 👍

**Comment by rolfschmidt** [comment]
Hi @mgruner :-) Thank you very much for the merge. Would it be possible to merge it also to rel-5_0?

**Comment by rolfschmidt** [comment]
im sorry please IGNORE!

**Comment by rolfschmidt** [comment]
Thank you a lot :-) :+1:  :+1:  :+1:  :+1:  :+1:  :+1:

**Pull request closed without merging**
