### PR TITLE
[ Master Bug 9038 ] - Default Ticket Type in Emails

### PR DESCRIPTION
**Pull request by s7design**
Hi @mgruner,

There is our proposal for fixing this bug. Actually, we did not fix the bug, we added not for invalid ticket types. We used ideas as this is fixed with invalid customer company for ticket information widget.
Maybe, we can change  style for customer note.

The problem is because ticket type is hardcore if it is not defined.
https://github.com/OTRS/otrs/blob/master/Kernel/System/Ticket.pm#L306

Generally, there could be such problems for other entities which is in meantime set to invalid. (e.g for Queue:Raw, for State:open ... and other entities which are often set as default )

Please, let me know what do you think about that. 

Regards
Zoran

### CODE REVIEW

**Comment by zottto** [comment]
Hi @s7design ,

I recommend to not fix it this way. The best solution would be a new sysconfig option "Default TicketType" and to assign that to the tickets (and not TypeID 1).
Additionally in the admin interface for the TicketType, if someone wants to set a type to invalid, you can check if this is the default type and not allow the change until the default type is changed, too.

We can keep the note in AgentTicketZoom additionally to inform the agents about tickets with invalid ticket types.

Would be great, if you could update the PR accordingly.

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

Thanks for the follow-up. I updated PR as you suggested. I updated unit test for Type as well.
If you have any suggestion please let me know.

Regards
Zoran

**Comment by zottto** [comment]
Hi @s7design,

looks really good already, but I recommend some slight changes:
- the Ticket::Type::Default should "default" by default (not "Unclassified")
- IMO the note that a type is invalid is not necessary in the customer interface
- at the moment, if the default type is assigned in the code, it is not checked that the default type really exists

At the moment, you are not able to change a ticket type if it is the default type. I would recommend to block the changes only if you change it to invalid and add a note to the screen, if you change the name to also update the sysconfig option Ticket:Type::Default accordingly.

Thanks,
Marc

**Comment by zottto** [comment]
Sorry, but the Ticket::Type::Default should be "Unclassified" by default as you already added it to the sysconfig. I tested that with an old system...

**Comment by s7design** [comment]
Hi @zottto 

Thanks for your suggestions it help me to improve code. I updated PR and there are also added new test cases in unit and Selenium tests.

Regards
Zoran

**Comment by zottto** [comment]
Thanks, was merged with bc4ff655004cc304f5202be8b1c62bb6e05cad24 (master) and fc84d63695a22bb92f20580c691906201625a0f6 (rel-5_0).

**Pull request closed without merging**
