### PR TITLE
Master - switched to Verified methods part1

### PR DESCRIPTION
**Pull request by s7design**
Hi @mgruner 

This is first part of the task for switch to Verified methods. I update some Selenium test randomly, but I am planing that we  continue  in some order one by one tests. I updated also AdminEmail.t and  AdminSignature.t which you committed 13 days ago. I wanted to cover all three methods.

Please let me know if you have any suggestion.

Regards
Zoran

### CODE REVIEW

**Comment by mgruner** [comment]
Looks good. At least in one place the VerifiedSubmit() would not be needed as no form reload is expected (error instead), but it is probably good to be consistent and use it whenever possible.

Whenever we cannot use it (because of closing window), a comment should be added explaining the reason IMHO.

If you go through the tests, this might be a chance of removing the Selenium based ticket creation in test files that should test other things. Right now usually AgentTicketPhone is called to create the ticket; this could be replaced by a simple backend call. What do you think?

**Comment by mgruner** [comment]
Merged, thank you very much! One more thing: can you please create all the future UT-related PRs for rel-5_0 as we need them there as well?

**Comment by mgruner** [comment]
I will then also cherry-pick them to master.

**Comment by s7design** [comment]
Thanks Martin,

I will make PRs for rel-5_0, it is not problem. And of course it is good advice that we create tickets in beckend where it is possible.

Regards
Zoran

**Pull request closed without merging**
