### PR TITLE
Sending articles with GI ops TicketCreate and TicketUpdate

### PR DESCRIPTION
**Pull request by jepf**
This PR is based on PR #815 from @fredericve 
Additionally, it adds support for attachments and extends the unit tests.

We made a public package for this:
https://github.com/znuny/Znuny4OTRS-GIArticleSend

### CODE REVIEW

**Comment by xhoy** [comment]
+1

**Comment by bzed** [comment]
+1 definitely a missing feature!

**Comment by xhoy** [comment]
Any reason this hasn't been merged jet?

**Comment by carlosfrodriguez** [comment]
Hi @jepf 

Thank you for your pull request, it was very good, unfortunately we can't merge it in OTRS 5.

I tried to port this to master a moth ago, but master branch changed so much since then, and at the moment it is very hard for me to keep it in sync. 

I also saw that it could be improved by adding security options (sign/encrypt) (with checks) similar to the ArticleCheck modules, for sure this will also need additional unit tests. (I tried in my port and it was working very well)

I guess that the best is to close this PR, please create a new one against master on its current state.

((enjoy))
cr

**Comment by bzed** [comment]
@carlosfrodriguez Really, shame on you. the first PR - on which this one was based - was opened in november 2015. And you even have been assigned on this PR in November 2016. Just closing it and letting others do the work because you failed to merge or even review it for a long time is... not nice.

**Comment by carlosfrodriguez** [comment]
Hi @bzed,
I know this has been open for long time, I would like to have it in OTRS as much as you do, but I would like to have it in the correct way.

If you find some time to update it to the latest changes in Master branch, dealing with the correct Ticket / Article separation and the handling of the new Omni channel infrastructure I would be glad to merge it, please remember to update the WSDL and the unit tests to cover the mail sending and verify.

((enjoy))
cr

**Comment by thorsteneckel** [comment]
@bzed we will provide the package linked by @jepf from now on for any upcoming OTRS versions 🚀 

@carlosfrodriguez you are free to take any inspiration or whatever from the repository and merge it into OTRS if you change your mind on the importance of this feature. All contributors of our repository have signed the CLA and we won't push any charges whatsoever. Please understand that we are not willing to take the effort and update the pull request. I regret that (our) contributions are appreciated that way.

**Comment by carlosfrodriguez** [comment]
Hi @thorsteneckel,

Thank you for your comments.

**Pull request closed without merging**
