### PR TITLE
Master - JS refactoring - Modify AdminCustomerUser

### PR DESCRIPTION
**Pull request by s7design**
Hi @mrcbnsls 

Hereby is updated AdminCustomerUser.tt.

Regards
Zoran

### CODE REVIEW

**Comment by mrcbnsls** [comment]
Hi Zoran,

Please remove the AddJSOnDocumentComplete() calls here, too. Thanks!

Marc

**Comment by s7design** [comment]
Hi @mrcbnsls

There is updated PR accordingly your suggestion. JS file is modified with Init function.

Regards
Zoran

**Comment by mrcbnsls** [comment]
Hi @s7design, I think something is wrong here, probably only the naming of the JS file. You named it Core.Customer.User.js, but it should be something like Core.Agent.Admin.CustomerUser.js, right?

**Comment by s7design** [comment]
Hello @mrcbnsls ,

Thank you for pointing this out. It was mistake from our side. Corrected JS name and updated PR.

Regards,
Zoran

**Comment by mrcbnsls** [comment]
Looks good for me, merged now in 70e6679. Thanks!

**Comment by mrcbnsls** [comment]
Could you maybe extend the UT (AdminCustomerUser.t) to also check for the functionalities used by AgentTicketEmail/-Phone? If you click on the "Customer User" link e.g. in AgentTicketPhone, an overlay shows up which contains an iFrame pointing to AdminCustomerUser;Nav=None. If you add a customer user then, this new user will be taken over automatically to the customer user field in AgentTicketPhone after creation. Please update the UT in a separate PR. Please let me know if you have any questions. Thanks!

**Pull request closed without merging**
