### PR TITLE
Master - JS refactoring - AdminGenericInterfaceWebservice

### PR DESCRIPTION
**Pull request by s7design**
Hello @zottto ,

Hereby is refactored AdminGenericInterfaceWebservice JS. Additionally there was missing 'fa fa-trash-o' class from TrashCan on delete action, added it.

Please let me know if you have any issues or comments regarding this PR.

Regards,
Sanjin

### CODE REVIEW

**Comment by zottto** [comment]
Hi Sanjin / @s7design,

please name the config option for the AddJSData() call correctly to avoid calling the Core.Config.Set() in JS again with the correct config name.

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

I fixed this PR. Honestly it was our oversight, sorry for that. As I mentioned in one of the previous PRs, we had a problem with adding data with the key in format like "Config.SomaName", and so we use this weird approach to solve this solution. It was wrong definitely. I hope now it is good, if you would like another naming for web-service data please let me know. 

Regards
Sanjin

**Comment by zottto** [comment]
Hi Sanjin / @s7design,

as discussed with Zoran: please update the AddJSData() call to only be called once with a Webservice data structure and keep the original naming on JS site.

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

As we have spoken via Skype, I updated this PR and renamed the JS data.

Regards
Zoran

**Comment by zottto** [comment]
Merged with 1a85110.

Thanks,
Marc

**Pull request closed without merging**
