### PR TITLE
SessionGetIDData GenericInterface operation

### PR DESCRIPTION
**Pull request by mfprimo**
The change from rpc.pl to Generic Interface lost the capability of get data about the agent currently connected.

### CODE REVIEW

**Comment by mgruner** [comment]
Hello @mfprimo, can I ask you to please sign our CLA as described on https://otrs.github.io?

**Comment by mgruner** [comment]
@carlosfrodriguez what do you think? I guess we'd need some unit test too, right?

**Comment by mfprimo** [comment]
Hi Martin,
  did you receive my subscribed CLA?

Cheers,
  Marco.

Il 03/12/2015 15:02, Martin Gruner ha scritto:
> Hello @mfprimo <https://github.com/mfprimo>, can I ask you to please
> sign our CLA as described on https://otrs.github.io?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OTRS/otrs/pull/856#issuecomment-161648610>.
> 

-- 
--------------------------------------------------------
Marco Ferrante (marco@csita.unige.it)
CSITA (Centro Servizi Informatici e Telematici d'Ateneo)
Universita' degli Studi di Genova - Italy
Via Brigata Salerno, ponte - 16147 Genova
tel (+39) 010 353-2621 (+39) 010 209-5556
--------------------------------------------------------

**Comment by mgruner** [comment]
Yes, thank you! :+1:

**Comment by carlosfrodriguez** [comment]
Hi @mfprimo,

Thank you for your pull request, I think there is some Auth missing, otherwise anyone can eventually get a list of active sessions information (including Name, Last name, Login, Email, etc) by adding Auth this is limited to valid users, I think this Auth should be only available for Agents, whine the complete operation should be prohibited for Customers.

As @mgruner already mention, I will be much better to get a unit test file for this operation, you can get more ideas by checking current unit tests for Generic Interface operation modules.

Please also remove the not needed settings from TicketSend in the XML config file :-)

I will be looking forward for the update of this Pull Request

((enjoy))
cr

**Comment by mfprimo** [comment]
I'm not sure that authentication has some meaning in this case: to obtain information about session data you need to know the session ID, and if you know a valid session ID you can authenticate yourself...
Session ID must be not predictable and must be transport using secure protocols, but nothing can block you to guess it randomly.
As mitigation measure, SessionGetIDData() invokes CheckSessionID() which detect changes in the remote IP address and removes expired sessions.
In fact, the goal of SessionGetIDData() is to obtain information about user own session (e.g. a list of queue available) in AJAX application, not to read data about other connected users.

**Comment by carlosfrodriguez** [comment]
Hi @mfprimo,

Please update your pull request, remove the TicketSend operation and add some unit tests you can use (scripts/test/GenericInterface/Operation/Session/SessionCreate.t) as an example.

Thanks

((enjoy))
cr

**Comment by carlosfrodriguez** [comment]
Hi @mfprimo,

Unfortunately the response can  not be defined in a WSDL unless it is changed to 

```perl
Data => {
    Session => [
        {
            Key => 'UserSessionStart',
            Value => '1293801801',
        },
        # ...
    ],
},
```

((enjoy))
cr

**Comment by mfprimo** [comment]
Hi,
  I don't fully understand the problem with the WSDL.
Could be sufficient to return an associative array in a Session variable? `E.g.`

`
Data => {
    Session => [
            UserSessionStart => '1293801801',
            UserRemoteAddr      => '127.0.0.1',
# ...
`

**Comment by carlosfrodriguez** [comment]
Hi @mfprimo,

I'm working already in a solution, at the moment only unit tests are missing. 

For the WSDL you need to specify all possible parameters and since session object foes not have a fixed amount, then it is not possible to specify it in a WSDL in the way to comment.

Besides that there are certain parameters that are not just strings, but complex structures. then they must be at least serialized, Im using JSON for that.

((enjoy))
cr

**Comment by carlosfrodriguez** [comment]
Hi @mfprimo,

This pull request mas merged with some changes and additions into https://github.com/OTRS/otrs/commit/b357a41d1f78e9e8c0ae9cffd0ce98f5e3371c91.

Many thanks for your dedication and effort! We will be looking forward for your next contributions.

((enjoy))
cr

**Pull request closed without merging**
