### PR TITLE
Master - JS refactoring - DashboardEventsTicketCalendar

### PR DESCRIPTION
**Pull request by s7design**
Hi @zottto 

Hereby is updated DashboardEventsTicketCalendar.tt. All JS code is moved to Core.Agent.Dashboard JS file.
Please let me know if you have any suggestions about this PR.

Regards
Zoran

### CODE REVIEW

**Comment by zottto** [comment]
Hi Zoran / @s7design,

loks good. Would you mind creating an extra private function for the calendar initialization and only call that function within Init()?

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

Yes of course it won't a problem, we will update this now.

Regards
Zoran

**Comment by s7design** [comment]
Hi @zottto 

PR is updated according to your feedback.

Regards
Zoran

**Comment by zottto** [comment]
Merged with 2d6b8cd.

Thanks,
Marc

**Pull request closed without merging**
