### PR TITLE
Feature/generic interface attachments

### PR DESCRIPTION
**Pull request by macjohnny**
add option to retrieve attachment contents or not, add fileID for attachments

similar to 

https://github.com/OTRS/FAQ/pull/7
https://github.com/OTRS/FAQ/pull/16
https://github.com/OTRS/FAQ/pull/58

### CODE REVIEW

**Comment by macjohnny** [comment]
@carlosfrodriguez can you have a look at this?

**Comment by macjohnny** [comment]
the unit tests need to be adapted. @carlosfrodriguez can you help me with that?

**Comment by carlosfrodriguez** [comment]
Hi @macjohnny 

I just want to understand better what is the intension of having the attachments without the content?

I see also that when content is not retrieved it also sets ContentAlternative to '' but if content is retrieved it doesn't seams to set it.

((enjoy))
cr

**Comment by macjohnny** [comment]
hey @carlosfrodriguez 
the reason for having attachments without content is to be able to display a ticket and list its attachments without running into memory / performance problems.
we can then load an attachment by setting the appropriate flag.

the "ContentAlternative" is set in `$TicketObject->ArticleAttachment()` https://github.com/macjohnny/otrs/blob/bbdd71a82a51b56f312f02d78007eb3b75940f81/Kernel/GenericInterface/Operation/Ticket/TicketGet.pm#L439 
in my changes I simply set its content to ''

**Comment by macjohnny** [comment]
hey @carlosfrodriguez 
could you have a look at this?
thanks

**Comment by carlosfrodriguez** [comment]
Hi @macjohnny,

Sorry about this long delay, I will try to review it ASAP, unfortunately im currently focus on OTRS 6 development. Please be patient a bit more.

((enjoy))
cr

**Comment by carlosfrodriguez** [comment]
Hi @macjohnny,

Thank you for your pull request, it was merged in https://github.com/OTRS/otrs/commit/62d22a6ffae263efd003053a37ef4dfe5e330f20, with small changes and additions.

((enjoy))
cr

**Pull request closed without merging**
