### PR TITLE
Master - JS refactoring - AgentTicketEmailOutbound

### PR DESCRIPTION
**Pull request by s7design**
Hi @zottto 

Hereby is updated AgentTicketEmailOutbound view. We moved JS code from TT to the new JS file.

Regards
Zoran

### CODE REVIEW

**Comment by zottto** [comment]
Hi Zoran / @s7design ,

please check again the usage of "$DynamicFieldNames" vs. "DynamicFieldNameStrg".
Does DynamicFieldNames really deliver an Array in JavaScript without any further converting?

If so, than DynamicFieldNameStrg in the perl file is not needed anymore and can be removed.

Is it possible to add tests for this use case?

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

Thank you for your feedback. DynamicFieldNames always delivers an Array in JS and DynamicFieldNameStrg is removed because it is not needed anymore.
We extended Selenium test to check for a JS refactored code.  First we wanted to do check with an ACL but that raised some problems so we decided to check for appearance of AJAX loader field before and after change state. 
If you have any suggestions how to improve test further on or additional comments let us know.

Regards
Zoran

**Comment by zottto** [comment]
Hi Zoran / @s7design,

the Selenium test is now failing for me:
 not ok 45 - AJAX Loader for 'DFtest14677055251' exists - JS function was run (is '0' should be '1')

Can you please check that again?

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

PR is updated regarding your suggestion.
Please let me know if you have any comment about these changes.

Regards
Zoran

**Comment by zottto** [comment]
Merged with 37fdddd.

Thanks,
Marc

**Pull request closed without merging**
