### PR TITLE
[ Rel-5_0 Bug 12458 ] - JavaScript events do not work when Customer History is loaded

### PR DESCRIPTION
**Pull request by s7design**
https://bugs.otrs.org/show_bug.cgi?id=12458

Hi @mgruner ,

Hereby is proposal for issue fix in screens where Customer History table is shown - AgentTicketPhone, AgentTicketEmail and AgentTicketCustomer.
JavaScript events like sorting, reply, etc. are added in Core.Agent.CustomerSearch.js and Selenium test is added accordingly.
Please let me know if there are any questions or issues regarding this PR.

Regards,
Zoran

### CODE REVIEW

**Comment by zottto** [comment]
He @s7design,

unit tests are also failing for this fix on rel-5_0:
+-------------------------------------------------------------------+
/ws/otrs/otrs5/scripts/test/Selenium/Agent/AgentCustomerHistory.t:
+-------------------------------------------------------------------+
...............................................................................................................................
 not ok 128 - TicketID 15 is found in expected row (is 'TicketID_16' should be 'TicketID_15')
............................................
=====================================================================

Can you fix this, too, please?

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

Of course it will be done soon.

Regrads
Zoran

**Comment by s7design** [comment]
Hi @zottto 

Selenium test is modified and sleeps are replaced with WaitFor.
Please let me know if you have any comment.

Regards,
Milan

**Comment by zottto** [comment]
Merged with 0783231.

Thanks,
Marc

**Pull request closed without merging**
