### PR TITLE
Add new feature: define default headers for emails

### PR DESCRIPTION
**Pull request by reneeb**
Sometimes someone might want to send some headers in *each* email sent via OTRS. Currently there is no way to define such headers. With this patch it would be possible...

### CODE REVIEW

**Comment by mgruner** [comment]
Hello @reneeb, thanks for your proposal. Can you please explain the use case a bit (this would be generally good for new features btw)? I am unsure if your example is really good for agent -> customer communication via email.
Regards, Martin

**Comment by reneeb** [comment]
Hi @mgruner, many mail servers do not send "out of office" replys for mails where those headers in the sample config are set. Some of my customers do not want any "out of office" replys at all, so they want to set the email headers.

Another use case is when OTRS "talks" to another system and you want to send a static X-Header to identify the system.

**Comment by mgruner** [comment]
Ok, understood, thanks. Can you please add the new config setting close to the existing Core::Sendmail settings? And please also extend a unit test or add a new one to cover this behaviour. Then I'll merge the  feature for OTRS 6. Best regards, Martin

**Comment by reneeb** [comment]
Thanks, I will do the needed changes...

**Comment by reneeb** [comment]
replaced by PR #982

**Pull request closed without merging**
