### PR TITLE
[Master - bug #11470] - AgentPreferences shows "My Services" even when Ticket::Service is disabled

### PR DESCRIPTION
**Pull request by s7design**
http://bugs.otrs.org/show_bug.cgi?id=11470

### CODE REVIEW

**Comment by s7design** [comment]
HI Martin,

This is my proposal for fixing this bug. Please let me know what do you think about that.

Regards
Zoran

**Comment by mgruner** [comment]
Hi Zoran,
would it perhaps be better to perform the check in PreferencesCustomService.pm?
Regards, mg

**Comment by s7design** [comment]
Hi Martin,

Thanks for suggestion.  I updated code. I believe that it is better now.

Regards
Zoran

**Comment by mgruner** [comment]
Merged, thanks Zoran!

**Pull request closed without merging**
