### PR TITLE
Fixed empty attachment ignoring and hardcoded english file size unit names

### PR DESCRIPTION
**Pull request by pboguslawski**
This mod fixes empty attachment handling in incoming e-mail messages
and web uploads and changes hardcoded english file size unit names
to universal symbols.

Related: https://dev.ib.pl/ib/otrs/issues/65
Related: http://bugs.otrs.org/show_bug.cgi?id=10509
Author-Change-Id: IB#1021851

### CODE REVIEW

**Comment by mgruner** [comment]
Hello Pawel,
thanks a lot for your proposal. How about a new method Main::HumanReadableFileSize() (with a few tests) to avoid the redundancy. And to be fully correct, we should use MiB/KiB/B.
Thanks and best regards, Martin

**Comment by mgruner** [comment]
Agreed.

**Comment by carlosfrodriguez** [comment]
Hi @pboguslawski 

Thank you for this large pull request, currently I have to ask 2 things...

1 You made some changes in Kernel/System/Web/Request.pm, are this needed for this pull request or we can put it into another one to make this more isolated? are there other cases like this?

2 Apparently the branch can not merge cleanly, would it be possible for you to rebase it?

((enjoy))
cr

**Comment by pboguslawski** [comment]
Hi,

> You made some changes in Kernel/System/Web/Request.pm, are this needed for this pull request

This is probably necessary for Kernel/System/Web/Request.pm > GetUploadAll() to handle empty attachment uploads, i.e. empty test.txt file.

> Apparently the branch can not merge cleanly, would it be possible for you to rebase it?

Accoring to [The Golden Rule of Rebasing](https://www.atlassian.com/git/tutorials/merging-vs-rebasing/the-golden-rule-of-rebasing) we don't use rebasing in public repos and recommed you to avoid it also. Just merged upstream changes to our feature branch and updated this PR (only CHANGES.md was not auto-merged). Please verify and consider merging.

Regards,
Pawel

**Comment by carlosfrodriguez** [comment]
Hi @pboguslawski 

Sorry for the delay, your pull request was merged in https://github.com/OTRS/otrs/commit/a2746ecec486be66202ec03873091544d706fb8a. with small changes and additions.

((enjoy))
cr

**Comment by carlosfrodriguez** [comment]
Hi @pboguslawski,

I had to rollback this fix since it does not work in Oracle, sending an empty string to Oracle is the same as sending NULL and the content field is marked as not null.

I suggest to split this pull request, one for the fix and another for the unit name changes (where I suggest also replace B with bytes).

This roll back was documented in https://github.com/OTRS/otrs/commit/d2f5cb12582abd328ef441727095bdc128eb2f97

((enjoy))
cr

**Comment by sb-otrs** [comment]
This has now been merged in https://github.com/OTRS/otrs/commit/95ba83851d251a54dbaf5113a4af84a68b494cf2.

Closing.

**Pull request closed without merging**
