### PR TITLE
Fixed bug #12429 - Nested form elements.

### PR DESCRIPTION
**Pull request by thorsteneckel**
See https://bugs.otrs.org/show_bug.cgi?id=12429 for further information.

### CODE REVIEW

**Comment by mgruner** [comment]
Hello @thorsteneckel. Thanks for your patch! When I try this, I cannot open the column settings in the ticket zoom any more. Clicking on the settings symbol has no effect. Can you check this please?

**Comment by thorsteneckel** [comment]
Thanks for your feedback! For sure. We'll take a look.

**Comment by mgruner** [comment]
@thorsteneckel, any news on this?

**Comment by thorsteneckel** [comment]
Hi @mgruner - yes! We are on it and will provide a fix for this next week. Sorry for the delay.

**Comment by thorsteneckel** [comment]
Done! See last commit.

**Comment by mgruner** [comment]
Hello @thorsteneckel. Strange, I still see problems with this. Here's what I did:

- open a ticket with linked tickets
bildschirmfoto 2016-12-02 um 13 50 44

- change the columns to add the "Age" column
bildschirmfoto 2016-12-02 um 13 51 00

- press "submit" - page is broken
bildschirmfoto 2016-12-02 um 13 51 11

I'm using chrome. Do you also see this?

**Comment by thorsteneckel** [comment]
We were able to reproduce it. Sorry. Fixed with the last commit.

**Comment by mgruner** [comment]
Ah! 👍  merged and backported to rel-5, thanks @thorsteneckel.

**Pull request closed without merging**
