### PR TITLE
Integrate TicketZoomDynamicFieldDisplay from OPAR: Show complete cont…

### PR DESCRIPTION
**Pull request by reneeb**
…ent of DynamicFields in AgentTicketZoom when the admin configured it...

### CODE REVIEW

**Comment by mgruner** [comment]
Seems like you're introducing a new undocumented value 2 in Ticket::Frontend::AgentTicketZoom###DynamicField, right? This should at least be documented on the config setting description. But I'm not fully convinced right now about it. Feels like an abuse of the setting and inconsistent to other places (2 = mandatory).

**Comment by reneeb** [comment]
If you want, I can use an other value...

**Comment by reneeb** [comment]
@mgruner Any idea what value should be used?

**Comment by mgruner** [comment]
Not really. But the general configurability is already there, it just does not distinguish by field. I'm closing this PR for now, please feel free to reopen with more information. Thanks a lot @reneeb.

**Pull request closed without merging**
