### PR TITLE
Add new config options to define hour and minute for pending time

### PR DESCRIPTION
**Pull request by reneeb**
Until now one can define the a time difference for the pending time. But in many cases, one want to set the pending time to the start of the office times to be reminded at the start of the work day.

This pull request adds exactly this. One can define the hour and minute of the pending time.

### CODE REVIEW

**Comment by xhoy** [comment]
+1!

**Comment by mgruner** [comment]
@nilei what's your opinion on this?

**Comment by jensoliver** [comment]
From my side it looks useful.

**Comment by nilei** [comment]
@mgruner, I understand the demand, but I think the actual issue is that selecting the right date and time is too cumbersome. I also do not fully understand how this new settings plays together with the old setting.

I would recommend to ease the date and time selection (not only for pending date and time), so one can e.g. jump to the beginning or end of the next office day. Bootstrap has nice date and time picker: https://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by reneeb** [comment]
@nilei the date is calculated with the old settings, only the hour and the minute is set with the new settings. Currently you just say "pending time is in 'now' in two days", with the new settings you say "It's in two days, but at 8 o'clock".

To ease the date/time selection is not the correct solution (but might be helpful anyways), because the agent would still have to set the correct hour/minute him/herself.

**Comment by nilei** [comment]
@reneeb, as said, I understand the demand and yes, it is useful!

Setting a global setting for users will always affect people positive and others negative. Turning this setting into a user preference or adding (custom) buttons (or similar) next to the pending time is more satisfying, even if you still need to do one click (better than 4 or more clicks as today).

@mgruner, I have no issues with merging, we may find a way to turn this into a user preference later :-)

**Comment by reneeb** [comment]
@mgruner Any news about the PR?

**Comment by nilei** [comment]
@reneeb, do you think you could enhance this to be pending state specific?

Example for **PendingTimeHour**:
- pending reminder => 8
- pending auto close+ => 17

**Comment by reneeb** [comment]
That should be possible... @mgruner what do you think about that?

**Comment by mgruner** [comment]
Hello all, and special thanks to @reneeb for the proposal!

Honestly, I am not convinced. The real problem is that the PendingDiffTime selection is too static and does not take into account the configured business hours. The current patch does not really solve this problem. If you are on a friday, you will still be presented with Saturday 8:00 even though this is not a working day.

@nilei I don't agree with making it even more specific, state dependent. There are far more criteria (priority etc.) that one could want to depend on.

To really fix this we'd probably need a different way of configuring the pending time default selection. I'm open for all suggestions.

Best regards, Martin

**Comment by reneeb** [comment]
@mgruner: It will *not* present Saturday 8:00 as the date is still calculated with respect to business hours. It's just the hour and the minute setting that is changed...

**Comment by mgruner** [comment]
@reneeb are you sure? AFAICT currently the PendingDiffTime is just 24h ahead, ignoring any configured business hours.

**Comment by nilei** [comment]
@mgruner, your are absolutely right, making it depending on the state is not a good enhancement, sorry for that :-)

**Comment by reneeb** [comment]
Argh, @mgruner you're right. Sorry for the noise...

**Pull request closed without merging**
