### PR TITLE
Master frontend usability - AdminCustomerCompany

### PR DESCRIPTION
**Pull request by s7design**
Hi @zottto 

Hereby is refactored AdminCustomerCompany. Breadcrumb and 'Save and finish' button are added and Selenium test are modified accordingly.
Please let me know if you have any comment on this PR.

Regards
Zoran

### CODE REVIEW

**Comment by zottto** [comment]
Hi Zoran / @s7design,

in 
https://github.com/OTRS/otrs/pull/1418/files#diff-841b6f13ee4ef6f3995a8afa8c3a8cfdR190

there is a notification added to $Output, but $Output is never used again?

Can you please check that?

Thanks,
Marc

**Comment by s7design** [comment]
Hello @zottto ,

Thanks for feedback. Corrected that mistake and updated PR. Removed notification if it is not found or possible to set dynamic field in this screen.

Regards
Zoran

**Comment by zottto** [comment]
Hi Zoran / @s7design,

after removing all notification the user now doesn't get notified anymore if something goes wrong with the dynamic field. 
It should be possible to see this notification, shouldn't it?

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

Thank you for feedback. Notification is now visible, but we are interested what behaviour is expected when 'Save' button is clicked and set dynamic field value error is appeared. Now if 'Save' is clicked and everything is ok, there is just page refresh, but if something goes wrong with setting dynamic field value, there is redirect to overview page with notification for this error.
All suggestions and comments are more than welcome.

Regards
Zoran

**Comment by zottto** [comment]
Hi Zoran / @s7design,

wouldn't it make more sense to also stay on the same page if something goes wrong and show the notification also after page refresh?

Marc

**Comment by s7design** [comment]
Hello @zottto ,

Added notifications and updated PR.

Regards
Zoran

**Comment by zottto** [comment]
Merged with 855124d.

Thanks,
Marc

**Pull request closed without merging**
