### PR TITLE
Fixed translatable messages to display translations

### PR DESCRIPTION
**Pull request by urbalazs**
Hi @mgruner 
This messages have complex HTML structure, when they are displayed on the notification bar, so they need to translated in place. Otherwise they remains untranslated.

### CODE REVIEW

**Comment by mgruner** [comment]
Can you try switching from ```Data => ...``` to ```Info => ...```? I would think that it should work then.

**Comment by mgruner** [comment]
There is actually no HTML included here so that ```Data``` would be needed, or do I miss something?

**Comment by urbalazs** [comment]
Hi @mgruner 
Thanks for the suggestion, changing "Data" to "Info" in the file UIDCheck.pm makes the string translatable in the interface. But in the AdminPackageManager.pm there are string concatenations, so only Translate() works there.

**Comment by mgruner** [comment]
Right! Merged and backported, thanks!

**Pull request closed without merging**
