### PR TITLE
Marked SysConfig options for translation

### PR DESCRIPTION
**Pull request by urbalazs**

### CODE REVIEW

**Comment by urbalazs** [comment]
Can anybody help me, why Travis test failed?

**Comment by s7design** [comment]
Hi @urbalazs 

I think that you have CodePolicy errors.

Maybe it could help you:

```
[checked] Kernel/Config/Files/Framework.xml
TidyAll::Plugin::OTRS::XML::ConfigDescriptionPlease make complete sentences in <Description> tags: start with a capital letter and finish with a dot.
Line 5547:                 <Description Translatable="1">HTML Reference</Description>

[checked] Kernel/Config/Files/ProcessManagement.xml
TidyAll::Plugin::OTRS::XML::ConfigDescriptionPlease make complete sentences in <Description> tags: start with a capital letter and finish with a dot.
Line 138:                 <Description Translatable="1">Create new process ticket</Description>
Line 276:                 <Description Translatable="1">Process Ticket</Description>

[checked] Kernel/Config/Files/Ticket.xml
```

You should put a period on the end of Description Value ( OTRSCodePolicy requires sentence for Description in config XML files)

Feel free to ask if you need some help about that.

Regards
Zoran

**Comment by urbalazs** [comment]
Hi @s7design 

Thanks for the help! Putting a dot at the end of description strings solved the issues. But now I have an other issue. I only marked strings for translation, so this issue is also not my fault (I think). Travis doesn't show me the end of the log, so I don't know, what's the problem.

**Comment by mgruner** [comment]
That's not your fault, it's a temporary error in the release branch.

**Comment by mgruner** [comment]
Hello Ur,
thanks for your proposal! For most strings I would not agree with your changes, as it makes not sense to translate example content or as the strings themselves are not really translatable (such as "TA" or "Deutsch", or log levels). I will close this PR for now; please feel free to update your branch and resubmit.
Best regards, Martin

**Pull request closed without merging**
