### PR TITLE
Ported to OM 16_12

### PR DESCRIPTION
**Pull request by s7design**

### CODE REVIEW

**Comment by mrcbnsls** [comment]
@mgruner, lets talk about this one once you're back.

**Comment by mgruner** [comment]
Hi S7, can you update this branch please so that it can be merged?

**Comment by s7design** [comment]
Hi @mgruner,

Yes we can of course.When you say update, do you think rebase this branch with master, or that we should go trough this PR and check it or something different.

All of that we will be able to do, this is not a problem but it is better to ask you before I do that.

Regards
Zoran

**Comment by s7design** [comment]
Hi @mgruner,

I rebased this, and tested Selenium test it works.
I hope now you can merge. If you have a problem let me know.

Regards
Zoran

**Comment by mrcbnsls** [comment]
Merged in 0a6cf14, thanks a lot!

**Pull request closed without merging**
