### PR TITLE
Fix bug#11022

### PR DESCRIPTION
**Pull request by noritnk**
Fix bug#11022.  See http://bugs.otrs.org/show_bug.cgi?id=11022

### CODE REVIEW

**Comment by mrcbnsls** [comment]
Hi @carlosfrodriguez, could you please have a look?

**Comment by carlosfrodriguez** [comment]
Hi @noritnk 
I Try your fix but it gives me some errors, for easy test you can add test cases to QueryCondition.t as:

```diff
diff --git a/scripts/test/DB/QueryCondition.t b/scripts/test/DB/QueryCondition.t
index 81275c6..5db26d4 100644
--- a/scripts/test/DB/QueryCondition.t
+++ b/scripts/test/DB/QueryCondition.t
@@ -1036,6 +1036,7 @@ for my $Query (@Queries) {
 %Fill = (
     Some0 => '0 otrs',
     Some1 => '1 otrs',
+    Some3 => '&& &&',
 );
 for my $Key ( sort keys %Fill ) {
     my $SQL = "INSERT INTO test_condition (name_a, name_b) VALUES ('$Key', '$Fill{$Key}')";
@@ -1062,6 +1063,13 @@ for my $Key ( sort keys %Fill ) {
             Some1 => 1,
         },
     },
+    {
+        Query  => '&& &&',
+        Result => {
+            Some3 => 1,
+        },
+    },
+
 );
 for my $Query (@Queries) {
     my $Condition = $DBObject->QueryCondition(
```

**Comment by noritnk** [comment]
Hi @carlosfrodriguez,
Thanks for the review.
I confirmed this change was wrong.  However, it is difficult for me to fix the bug by minor changes.
If we achieve it, some potential bugs will leave there.  So now I sent new PR to make large changes,
and add test cases there.  It enables to simpilify QueryCondition.
https://github.com/OTRS/otrs/pull/435

**Comment by mrcbnsls** [comment]
Closing because new PR has been opened which includes the changes. CR, I assigned it to you. Thanks Norihiro!

**Pull request closed without merging**
