### PR TITLE
Master - JS refactoring - AgentDashboardStatsSettings

### PR DESCRIPTION
**Pull request by s7design**
Hello @zottto ,

Hereby is refactored AgentDashboardStatsSettings. While working on this, changed a bit JS for initialisation of stats widget on dashboard. Moved InitStatsWidget into separated function and created private one that calls creation of stats widget. Now everything works, stats settings and rendering of statistics on save changes.

Please let me know if you have any issues or questions regarding this PR.

Regards,
Sanjin

### CODE REVIEW

**Comment by s7design** [comment]
Hello @zottto ,

This PR is rebased and ready for review.

Regards,
Sanjin

**Comment by zottto** [comment]
Hi Sanjin / @s7design,

please use PubSub events also on initializing the StatsWidget (in PrefUpdate).

Marc

**Comment by s7design** [comment]
Hello @zottto ,

Thanks for follow up. PR is updated and ready for review.

Please let me know if you have any issues or questions regarding last changes.

Regards,
Sanjin

**Comment by zottto** [comment]
Merged with 32a6304.

Thanks,
Marc

**Pull request closed without merging**
