### PR TITLE
Add nested group support for LDAP user/group sync

### PR DESCRIPTION
**Pull request by fraenki**
As requested in https://github.com/OTRS/otrs/pull/1344#issuecomment-414325847 here's a new pull request.
For a full description please click here: https://github.com/OTRS/otrs/pull/1344#issue-77153052.

### CODE REVIEW

**Comment by fraenki** [comment]
@mgruner The original PR was already two years old. Maybe you could reassess if this can be included in OTRS or if changes are required. Thanks in advance!

**Comment by s7design** [comment]
Hi,

Thanks for PR.

If you would like to make new PR, what is welcomed always, please subscribe OTRS contributor agreement on the site http://doc.otrs.com/

Regards
Zoran

**Comment by fraenki** [comment]
@s7design Are you going to merge this PR? :)

**Comment by s7design** [comment]
Hi,

We will test if it is possible in this moment, for that it would be great if you can write some test to cover your test case.

Regards
Zoran

**Comment by fraenki** [comment]
> We will test if it is possible in this moment, for that it would be great if you can write some test to cover your test case.

As stated by @mgruner [here](https://github.com/OTRS/otrs/pull/1344#issuecomment-318030557), LDAP tests are not required for this PR.

**Comment by s7design** [comment]
Hi,

I made new branch feature-LDAPnestedgroup-zi-rel-6_0, we will follow test results. There was some failed test because of code policy.

Regards
Zoran

**Comment by fraenki** [comment]
@s7design Is there anything left to do for me?

**Comment by s7design** [comment]
Hi,

It is merged here 

https://github.com/OTRS/otrs/commit/b9d0630abf0dba792e77b0db91e2eec1d78d1eb2

Thanks a lot  for your work.

Regards
Zoran

**Comment by s7design** [comment]
Hi,

We had to revert this:

https://github.com/OTRS/otrs/commit/13d441f59440b5ca94be92cf8c1f03ea09b6a78c

There is some problem, we will update PR with more details soon.

Regards
Zoran

**Comment by fraenki** [comment]
> There is some problem, we will update PR with more details soon.

I'm curious as to what problem it could have caused. We're using this feature for almost 3 years in production now.

**Comment by s7design** [comment]
Hi Frank,

After the careful review, we had to revert your change. The reasons are outlined below:

1. Adding new system perl dependencies to patch level is not possible by our guidelines. The problem is that the existing systems and our update procedures do not expect new conditions to run the software. Is not even clear why a new requirement was added, because the URI library is part of the bundled 'cpan-lib' folder? It is recommended to remove the requirement, usage in the code should still be possible.

2. Adding new features in the patch level updates is not possible by our guidelines. Patch levels generally contain fixes without major changes in functionality in order to maintain stability in production systems and to provide them with a simple update path. This could be added in the next major version (OTRS 8), but there is no guarantee yet (see below).

3. Lack of tests is a big problem. We still do not have covered LDAP functionality, and we can not be sure that with this new feature we will not risk the stability of the existing code. We are aware that neither basic LDAP support is covered, and therefore we consider we should test the current implementation at first (for example, LDAP mocking in the UT environment), and only then extend it. Since this is a big task, we do not expect the reporter to do all of that by themselves, but we ask for patience until it is ready.

We have no problem believing the reporter that his proposal works, even in production environment for some time, but with the professional code development approach we have in place and taking responsibility for new features in next releases, it is not advisable to merge this PR until all the listed conditions are satisfied.

Thank you for your patience and your hard work.

Regards
Zoran

**Comment by fraenki** [comment]
@s7design see my comments below.

1. I was not aware of the bundled library. I think it would be OK to rely on the bundled library instead of adding a new dependency. Should I remove the dependency from this PR?
1. Please be aware that my original submission dates back to **2016**. Back then it was targeted for OTRS 6 (unreleased at that time). Besides that I did not propose to violate the OTRS guidelines. Feel free to merge it for inclusion in OTRS 8 or whatever is in compliance with the guidelines.
1. As stated in your comment, it's up to the OTRS maintainers to add tests for basic LDAP support first. But I respectfully disagree that such tests would be a strict requirement to get this PR merged. It's not like I've added thousands lines of code. This proposal contains only a few lines of rather simple code that could easily be reviewed and tested (manually) to confirm that it does not break basic functionality, IMHO. So in my opinion it's an unnecessary burden to declare brand new tests a requirement for this PR.

Furthermore, please be aware that this feature is DISABLED by default. So existing installations won't be affected at all.

Honestly, this is a huge disappointment. It was already stated in 2017 by @mgruner that new tests cannot be a requirement for this PR (https://github.com/OTRS/otrs/pull/1344#issuecomment-318030557). And now 1 1/2 years later we are back on the exact same topic. :(

**Comment by fraenki** [comment]
A friendly reminder that 9 months later still no reply or anything else. Pretty discouraging. :-/

**Comment by mgruner** [comment]
Dear @fraenki, you are completely right. This is a disappointing situation. I can now see that also for OTRS 8 we will not have the needed time to setup the required environments and find a strategy to make this auto-testable.
Therefore I'll close this PR now to no longer convey the impression that we can merge it anytime soon. As always, the code stays available here in github for anyone who wants to use or build on it.
Sorry, and all the best, Martin

**Comment by fraenki** [comment]
LOL

**Pull request closed without merging**
