### PR TITLE
Added ACL Action

### PR DESCRIPTION
**Pull request by florianedlhuber**
Added ACL Action AgentAppointmentCalendarOverview because it is missing.

### CODE REVIEW

**Comment by mgruner** [comment]
@dvuckovic could you please check this?

**Comment by dvuckovic** [comment]
@florianedlhuber Thanks for the proposal.

However, I'm failing to understand the use-case behind this change? What's the expected usage of this new third-level param for ticket ACLs?

When I apply your change to a local system, I do get the action name in the autocomplete list and can choose it, but this screen does not really support ticket ACLs. The same goes for other screens unrelated to tickets in the system, which are also not listed here (e.g. AgentDashboard, AgentCustomerInformationCenter, etc).

I might be missing something obvious, though, so please outline an example for us.

Thanks!

Regards,
Dusan

**Comment by florianedlhuber** [comment]
It's not for the view, It is to remove the new appointment button in ticket menu. Useful if you need to restrict it for a specific role. Any ticket menu action should be available in the ACLs.

**Comment by mgruner** [comment]
@s7design I think you are familiar with this. Can you please check if it is still relevant?

**Comment by s7design** [comment]
Applied thanks to  florianedlhuber.

Regards
Zoran

**Pull request closed without merging**
