### PR TITLE
Master frontend usability - AdminQueueAutoResponse

### PR DESCRIPTION
**Pull request by s7design**
Hi @zottto 

Hereby is refactored AdminQueueAutoResponse. Breadcrumb and 'Save and Finish' button are added.
Selenium test is modified with breadcrumb checking.
Please let me know if you have any feedback on this PR.

Regards
Zoran

### CODE REVIEW

**Comment by s7design** [comment]
Hi @zottto 

This PR is updated, there is added notification

Regards
Zoran

**Comment by s7design** [comment]
Hi @zottto 

The PR is updated, the notifications are deleted.

Regards
Zoran

**Comment by zottto** [comment]
Hi @s7design,

can you please add another level in the breadcrumb for the special filter Action=AdminQueueAutoResponse;Filter=QueuesWithoutAutoResponses ?

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

PR is updated, breadcrumb item is added as you suggested.

Regards
Zoran

**Comment by mrcbnsls** [comment]
Merged in 6c0dad2, thanks!

**Pull request closed without merging**
