### PR TITLE
[ Rel-4_0 bug Bug 11510 ] - AgentTicketMove empty by sysconfig changes

### PR DESCRIPTION
**Pull request by s7design**
http://bugs.otrs.org/show_bug.cgi?id=11510

Hi @mgruner 

I provided PR for rel-4_0 as well, because the reporter mark this brunch in the bug report. I also fixed some spelling mistakes in AgentTicketMove.pm

Regards
Zoran

### CODE REVIEW

**Comment by rolfschmidt** [comment]
Thank you very much for the fast pull request :+1:

**Comment by carlosgarciac** [comment]
Hi Zoran,

Queue is not an option on SysConfig for this screen and should always be visible and it is expected on the server for saving data, then I think the complete IF for checking elements on config should be removed and the 'WidgetTicketActions' block as well, on .pm and .tt files.

Please let me know your comments about it.

Regards,
Carlos Garcia

**Comment by s7design** [comment]
Hi @carlosgarciac 

I updated PR. I agree with you it is better solution now. WidgetTicketActions block is not needed any more, because there is necessary at least field  for new queue.
Thanks for suggestion.

Regards
Zoran

**Comment by s7design** [comment]
I make new PR for OTRS5 as well ( https://github.com/OTRS/otrs/pull/766 )

Regards
Zoran

**Comment by carlosgarciac** [comment]
Hi @s7design,

Thanks a lot for your PR, it was merged on 424281d.

Best regards,
Carlos García

**Pull request closed without merging**
