### PR TITLE
Improvement of QueryCondition.

### PR DESCRIPTION
**Pull request by noritnk**
I see that QueryCondition is some potential bugs.  This PR makes a change to simplify QueryCondition.
This PR includes fix for bug#11022.

By the way, the change enables to parse an input with not the character unit but  the word unit.

### CODE REVIEW

**Comment by carlosfrodriguez** [comment]
Hi @noritnk,

Thank you for the update, unit test work like a charm, however i'm not 100% sure if we should integrate this into rel-4_0, or just in master, as this is a BIG change in the query condition mechanism. Please be patient I will followup ASAP after some internal discussions about the topic.

((enjoy))
cr

**Comment by noritnk** [comment]
Hi @carlosfrodriguez,

Thanks for the review.

> Thank you for the update, unit test work like a charm, however i'm not 100% sure if we should
> integrate this into rel-4_0, or just in master, as this is a BIG change in the query condition
> mechanism. Please be patient I will followup ASAP after some internal discussions about the topic.

Sure.

Thanks.

**Comment by carlosfrodriguez** [comment]
Hi @mgruner,

Can you please take a look on this pull request?

((enjoy))
cr

**Comment by mgruner** [comment]
Hello @noritnk, this looks quite nice. Can I ask you to please make this PR for master? And add more documentation in the perl code, to explain what the several steps in the code do (with examples)? Some more unit tests would be nice too, as you mention "potential bugs".
I'll close this PR for now as it is against 4.0 and we are not going to apply it there unless critical bugs force us to do so. Please reopen a new PR for master.
Thank you very much!

**Pull request closed without merging**
