### PR TITLE
Master - JS refactoring - AgentDashboardTicketGeneric

### PR DESCRIPTION
**Pull request by s7design**
Hello @zottto ,

Hereby is last JS refactored module AgentDashboardTicketGeneric. 
To begin with, please bear in mind that this is proposal and there is still room to improve this code. There's a lot of repetition code which could be refactored further on and made a bit more dynamically. Gonna outline change that differs from just moving JS from TT. 

Removed three functions in Core.Agent.Dashboard.js; InitCustomerIDAutocomplete(), InitCustomerUserAutocomplete() and InitUserAutocomplete(). These events are handled via Core.Agent.TableFilters.js and those function are redundant in Core.Agent.Dashboard.

There is some code from AgentDashboardCommon refactoring, due to logic used there to go through every dashboard widget. Once that PR is merged, I will rebase this PR for easier review.

Please if you have any issues, questions or problems while reviewing and later merging this PR, do not hesitate to contact, I will be more then glad to assist in any possible way.

Regards,
Sanjin

### CODE REVIEW

**Comment by s7design** [comment]
Hello @zottto ,

This PR is rebased and ready for review.

Regards,
Sanjin

**Comment by zottto** [comment]
Also on this PR it would be nice to use PubSub for the re-init after contentupdate.

Marc

**Comment by s7design** [comment]
Hello @zottto ,

Included PubSub in this PR and rebased it on current master.

Please let me know if you have any issues or questions.

Regards,
Sanjin

**Comment by zottto** [comment]
Hi Sanjin / @s7design,

can you please rebase this?

Thanks,
Marc

**Comment by s7design** [comment]
Hello @zottto ,

This PR is rebased and ready for review.

Regards,
Sanjin

**Comment by zottto** [comment]
Merged with 26226a5.

Thanks,
Marc

**Comment by zottto** [comment]
Hey Sanjin / @s7design,

Selenium tests are failing for this (TicketGeneric.t). It looks like sorting of filterable columns is not working correctly. At least sort icons (arrows up / down) are missing.

Can you have a look please?

Thanks,
Marc

**Comment by s7design** [comment]
Hello @zottto ,

I will take a look right away.

Regards,
Sanjin

**Comment by s7design** [comment]
Hello @zottto ,

PR is updated. There was small error on click hybrid columns and sorting them. Selenium test is performing as expected now.

Regards,
Sanjin

**Comment by zottto** [comment]
Merged with 6b14e72 (again).

Thanks,
Marc

**Pull request closed without merging**
