### PR TITLE
Master - JS refactoring - Modify AdminSalutation

### PR DESCRIPTION
**Pull request by s7design**
Hi @mrcbnsls 

Hereby is updated AdminSalutation. I did not extend AdminSalutation with the test for the filter. We are also planing to cover JS unit tests for all JS and there we will test InitTableFilter as well. However, this filter is tested in other screens ( e.g. here also https://github.com/OTRS/otrs/pull/1193/files )

If you would like we will be able to add this test case in  AdminSalutation.t 

Regards
Zoran

### CODE REVIEW

**Comment by mrcbnsls** [comment]
Please create a separate JS file here, too. Thanks!

**Comment by s7design** [comment]
Hi @mrcbnsls 

This PR is updated as well.

Regards
Zoran

**Comment by mrcbnsls** [comment]
Merged in f8d2c74, thanks. I also added a filter block here.

**Comment by mrcbnsls** [comment]
Just saw that the namespace was not named correctly, which I fixed in b809b00. Please make sure that the namespace always matches the right frontend! Thanks!

**Pull request closed without merging**
