### PR TITLE
Follow-up for bug#13239

### PR DESCRIPTION
**Pull request by urbalazs**
Hi @sanjinvik and @zilibasic 
This is a follow-up fix for [bug#13239](https://bugs.otrs.org/show_bug.cgi?id=13239), because the displayed text of checkbox is "Enabled". So in my opinion the word "active" or "inactive" are not correct.
I changed all occurrence of "active" or "inactive".
This pull request affects many strings. Can you please sync to Transifex in order to be translated in 6.0.1?

### CODE REVIEW

**Comment by mgruner** [comment]
Hello @urbalazs, can you please update this? We needed to make bigger changes to the XML for an important fix. Sorry for the inconvenience.

**Comment by urbalazs** [comment]
Hi @mgruner 
I tried to resolve the conflict here in GitHub. Can you check, that it can be merged now? I haven't do such thing yet.

**Comment by mgruner** [comment]
It does not seem to have worked, github still reports merge conflicts. Another alternative could be to send a fresh PR instead of this one, not sure what is better.

**Comment by urbalazs** [comment]
Hmm...
I see green tick with text "This branch has no conflicts with the base branch".

**Comment by mgruner** [comment]
Now it works, right!

**Comment by mgruner** [comment]
Merged and backported, thanks @urbalazs!

**Pull request closed without merging**
