### PR TITLE
integrate MyLastChangedTickets dashboard widget from OPAR

### PR DESCRIPTION
**Pull request by reneeb**
Hi,

this is my first pull request for OTRS6. I'd like to integrate some of my addons I published on OPAR in Core-OTRS....

- Renée

### CODE REVIEW

**Comment by reneeb** [comment]
@mgruner any news about this PR?

**Comment by mgruner** [comment]
@nilei, @ManuelHecht: Nils and Manuel, what do you think about this feature proposal?

**Comment by nilei** [comment]
@mgruner, the idea to see "your last changed tickets" is very good but I would like to see this as an enhancement to the ticket search module, so one could configure own dashboard modules showing e.g. "Your last changed **Incident** tickets" or "Your last changed **Service Request** tickets" when combined with other search parameters.

**Comment by nilei** [comment]
@reneeb, may you implement my recommendations?

**Comment by mgruner** [comment]
I'm closing this PR for now. Let's revisit the issue when there are updates. Thanks!

**Pull request closed without merging**
