### PR TITLE
Submit with Ctrl+Enter in textareas

### PR DESCRIPTION
**Pull request by Perleone**
Will not work if RichText is enabled!

### CODE REVIEW

**Comment by mrcbnsls** [comment]
Hi @Perleone, thanks a lot for your contribution. I have some remarks:

- This should be improved to be compatible with OS X, too. Event.ctrlKey will not work there.
- I'm not sure if #submitRichtext is present everywhere. I think we should make sure that the submit button of the current form is used rather than one with a hardcoded ID.

Could you please update the PR with the requested changes? Thanks a lot!

**Comment by Perleone** [comment]
> Could you please update the PR with the requested changes?

@mrcbnsls Done and done, checks passed successfully.

**Comment by Perleone** [comment]
_"Once more unto the breach, dear friends, once more!"_

**Comment by Perleone** [comment]
@mgruner The Travis CI bujild against Perl 5.20 and PostgreSQL fails on `/home/travis/build/OTRS/otrs/scripts/test/PostMaster/CommunicationLog.t:` with 
> Message: ERROR:  could not extend file "base/16387/16792": wrote only 4096 of 8192 bytes at block 381
> HINT:  Check free disk space.,
You might want to look at the Travis configuration. Or trigger a rebuild. Or both. :)

**Comment by mrcbnsls** [comment]
Thanks a lot! Merged with a small change: I changed the binding to be a bit more greedy, so dynamically loaded textareas will be considered (e.g. in process tickets), too.

**Pull request closed without merging**
