### PR TITLE
Master - Selenium - Modularised AgentTicketZoom

### PR DESCRIPTION
**Pull request by s7design**
Hello @mgruner ,

Hereby are created Selenium tests for modularised AgentTicketZoom. Created four test covering TicketInformation, CustomerInformation, LinkTable and ProcessInformation.

Test cases consisting of disabling/enabling modules, toggling actions and reading different possible parameters in them. 

Please let me know if there are any questions or issues regarding these tests.

Kind Regards,
Sanjin

### CODE REVIEW

**Comment by mgruner** [comment]
Hello Sanjin,
looks very nice so far. Regarding the link table, you could test simple and complex mode, please. The table will be on the sidebar OR in the main column. Regarding the escalation tests, please make sure not to get into problems outside of business hours; maybe add a 24/7 calendar with no vacation like in other tests?
Regards, mg

**Comment by s7design** [comment]
Hello @mgruner ,

Selenium tests are updated as you suggested. Thank you for reminding me about those details. 

Let me know if i can do anything else regarding these tests.

Regards,
Sanjin

**Comment by mgruner** [comment]
Hello Sanjin,
thanks. I get the following error in ProcessInformation.t: 
```not ok 58 - Exception in Selenium': An element could not be located on the page using the given search parameters: //p[contains(@title, 'Shipping' )],xpath at (eval 100) line 136.```
Regards, mg

**Comment by s7design** [comment]
Hello @mgruner ,

This is interesting error. In my environment test perform as expected. Added some additional input information, subject and body on process creation. Perhaps it was crashing there and process ticket was never created, which could cause error you experienced.

Please let me know if it's working now.

Regards,
Sanjin

**Comment by mgruner** [comment]
Still fails. The process ticket is in the activity "Make order" and not "Shipping" as suggested by the test case.

**Comment by s7design** [comment]
Hello @mgruner ,

Modified test to prevent issue you are experiencing. Please let me know if these changes are working in your test environment now.

Regards,
Sanjin

**Comment by mgruner** [comment]
I see the same error.

**Comment by s7design** [comment]
Hi @mgruner 

I updated this PR and ProcessInformation.t Selenium test. There were some tricky issues. In some cases process was not created. I added some checks and wait-time to avoid such problems. 

I tested it and it works fine for me now. Please let me know if it works in your system as well.

Regards
Zoran

**Comment by mgruner** [comment]
Works fine now, thank you! Merged.

**Pull request closed without merging**
