### PR TITLE
Added Sysconfig Option to define the default gravatar image for artic…

### PR DESCRIPTION
**Pull request by andreashergert1984**
…lelist if no one is present

configuration:
Frontend::Gravatar::ArticleDefaultImage

### CODE REVIEW

**Comment by florianedlhuber** [comment]
Great 👍🏻

**Comment by Rooobaaat** [comment]
Like that! 👍

**Comment by nilei** [comment]
Must have !!! 

I am on site right now where we had to disable it because the identicon turned into a "Hakenkreuz". This is not OTRS fault of course, and we already can configure an alternative for agent users, but this PR will also make that possible for customer user senders. The default value btw. should be changed to "mm" instead of "identicon"!

Cheers, Nils

**Comment by mrcbnsls** [comment]
Merged in 5da1d52a277e75eb9d77e5b2269a10ae7bf1b69e, thanks!

**Pull request closed without merging**
