### PR TITLE
Allow array as top-level-XML-Element on REST Response from remote site.

### PR DESCRIPTION
**Pull request by andreashergert1984**

### CODE REVIEW

**Comment by Rooobaaat** [comment]
👍

**Comment by mgruner** [comment]
@s7design can you please handle this? Some tests are probably in order.

**Comment by s7design** [comment]
@mgruner no problem we will check this

**Comment by s7design** [comment]
Hello @andreashergert1984 

This is merged in master https://github.com/OTRS/otrs/commit/f1bd8d7451c20fa354651b0ae8d6660d19f52427 and rel-6_0 https://github.com/OTRS/otrs/commit/b8d279a44ba51c52a0d7e98fd943147278890a8c. Thank you.

Regards,
Milan

**Pull request closed without merging**
