### PR TITLE
More Company related columns in ticker related dashboard widgets

### PR DESCRIPTION
**Pull request by execthis**
Added more Company related columns like CompanyName, CompanyCountry... in ticket related dashboard widgets. But Columns are only available if CustomerCompanySupport is enabled.

### CODE REVIEW

**Comment by mrcbnsls** [comment]
Hi @execthis, please see Martin's comments on your PR. I'll close it for now as you didn't work on it for some time. Please just create a new one (with a reference to this one) once you have been able to implement the requested changes. Thanks!

**Comment by nilei** [comment]
@execthis, @mrcbnsls, @mgruner 

Can we have this implemented in some fashion for OTRS 6? It is really useful if agents can see customer details in the ticket overviews. Regarding the terminology, I recommend to avoid the word "Company" as it too much related to the meaning of an external company. Many setups are only for internal support and here "Company" is very confusing for the agents. My recommendation is still "Customer" and "CustomerUser" but I understand that this syntax makes it hard to filter in some circumstances. Instead we could use "CustomerOrganization" and "CustomerUser". There are some other placed where this is not consistent, e.g. CustomerKey vs. CustomerUserID vs. CustomerUserLogin and "Customer name" (e.g. OTRS AG) vs. "CustomerName" (e.g. John Doe) - but this is of course another story to be fixed by another pull request.

Anyway, showing customer and customer user details in the ticket dashboard, overviews, statistics, customer and customer user and ticket searches, etc. would be a great step forward!

-- Cheers, Nils

**Comment by mgruner** [comment]
@nilei we are talking here about internal columns that are related to the database. There it is ok to use "Company" I believe.

**Comment by nilei** [comment]
Hi @mgruner, also Admins are sometimes just users ;-)

But yes, for now we can stay with the old notation and have a "notation clean up" for a later OTRS version :-)

Cheers, Nils

**Pull request closed without merging**
