### PR TITLE
Master - JS refactoring - AgentDashboardStats

### PR DESCRIPTION
**Pull request by s7design**
Hello @zottto ,

Hereby is refactored AgentDashboardStats JS. 

Please let me know if you have any issues or questions regarding this PR.

Regards,
Sanjin

### CODE REVIEW

**Comment by zottto** [comment]
Merged with 20d30e8.

Thanks,
Marc

**Comment by zottto** [comment]
Do you have AgentDashboardStatsSettings on your list?

**Comment by s7design** [comment]
Hello @zottto ,

Yes we have, but was waiting for AgentDashboardCommon to refactor first, since it is closely connected to it.

Regards,
Sanjin

**Comment by zottto** [comment]
ok, thanks. :-)

**Pull request closed without merging**
