### PR TITLE
TicketSearch: Allow filtering for non-empty dynamic fields

### PR DESCRIPTION
**Pull request by moritz**
This builds on PR #1482 to allow `Empty => 0` in a TicketSearch for a dynamic field, to search for tickets with a non-empty aka present dynamic field.

### CODE REVIEW

**Comment by moritz** [comment]
Any feedback? Can we hope for a merge soon?

**Comment by mgruner** [comment]
Hello Moritz,

sorry, we are very busy with the release of OTRS 5s that is due soon. I will make sure to give you feedback on this as time permits, it will not be forgotten.

Best regards,

Martin Gruner
Team Lead R&D

OTRS AG
Bahnhofplatz 1a
94315 Straubing

T: +49 (0)6172 681988 0
F: +49 (0)9421 56818 18
I:  www.otrs.com/

Geschäftssitz: Bad Homburg, Amtsgericht: Bad Homburg, HRB 10751, USt-Nr.: DE256610065
Aufsichtsratsvorsitzender: Burchard Steinbild, Vorstand: André Mindermann (Vorsitzender), Christopher Kuhn, Sabine Riedel

OTRS 5s – Modernste Technologie und höchste Sicherheit – die neuen Features für OTRS Free, OTRS Business Solution™ und OTRS Business Solution™ Managed! Erscheinungsdatum 01. November.
Jetzt entdecken! https://www.otrs.com/otrs-5s/?lang=de&utm_id=569

**Comment by mgruner** [comment]
Merged with small changes in 5714babb77f8c458e0f64b9d91480e7cc237f5c8. Thanks @moritz and @rolfschmidt!

**Comment by rolfschmidt** [comment]
nice @mgruner 👍

**Pull request closed without merging**
