### PR TITLE
Master - JS - AgentTicketSearch - events fix

### PR DESCRIPTION
**Pull request by s7design**
Hello @zottto ,

Hereby is small fix for JS events in AgentTicketSearch. There has been mistake on our side while refactoring this module. Added hook for Core.UI.ActionRow.js to load with footer and added Core.Agent.Overview.js to AgentTciektSearch module loader. 

SelectAllTickets, column sorting and ShowContentSettingDialog are working as expected now. Please let me know if you disagree with these changes.

Regards,
Sanjin

### CODE REVIEW

**Comment by zottto** [comment]
Merged with f9ab416.

Thanks,
Marc

**Comment by mrcbnsls** [comment]
Had to revert this because the following UT were constantly failing:

AgentTicketResponsibleView
AgentTicketStatusView
AgentTicketBulk

Can you please check this, @s7design? Thanks!

**Comment by s7design** [comment]
Hi @mrcbnsls 

Yes of course we will check that.

Regards
Zoran

**Comment by s7design** [comment]
Hello,

Updated and rebased PR. Hopefully error that was showing is solved, we will keep an eye on travis respond.

Regards,
Zoran

**Comment by zottto** [comment]
Merged (again) with 74a0afa.

**Pull request closed without merging**
