### PR TITLE
[Master - Bug 11067]  Uncheck of Roles when using a filter.

### PR DESCRIPTION
**Pull request by s7design**
http://bugs.otrs.org/show_bug.cgi?id=11067

Hi @mgruner 

Here is fixed the filter in admin screens, actually this PR is updated old one which there was for rel-4_0. 
We also added some test for this feature. We tested it only in AdminRoleGroup, AdminRoleUser, AdminUserGroup. If you want we will be able to add tests for other screen as well ( e.g. AdminCustomerUserGroup, AdminCustomerUserService, AdminQueueTemplates ...)

Regards
Zoran

### CODE REVIEW

**Comment by mgruner** [comment]
Hello Zoran,
can you please rebase this PR, there are merge conflicts currently?
Regards, Martin

**Comment by s7design** [comment]
Hi Martin,

This is rebased. I tested it manualy in GUI and with Selenium tests which are changed in this PR. All works fine now. 

Regards
Zoran

**Comment by s7design** [comment]
This is again rebased wit up to date master.

Regards
Zoran

**Comment by s7design** [comment]
Hi @mgruner  and @mrcbnsls 

I rebased this PR and added test for AdminQueueTemplate because of the bug http://bugs.otrs.org/show_bug.cgi?id=11735

Regards
Zoran

**Comment by zottto** [comment]
Hello @s7design ,
can you please rebase this PR again? There are merge conflicts currently.
I can merge it this week (after rebasing).

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

I rebased this PR and improved test a little bit. I hope it works fine now.

Regards
Zoran

**Comment by s7design** [comment]
Hi @zottto 

I updated PR again, I saw some error in Travis. Actually, I tidy-up Core.Form.js script by OTRSCodePolicy. I thought that I had done it yesterday, but maybe I pushed it without one commit. I suppose it is better now.

Regards
Zoran

**Comment by zottto** [comment]
Hi @s7design,

UnitTests are still failing. Can you please check again?

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

Yes I saw. It is a little bit strange, because it works on my system. I see that Travis show some error in test OTRSCodePolicy. 
I am trying to fix it, I call CodePolicy before commit and I did not have any messages.

I hope it will be fixed very soon.

Regards
Zoran

**Comment by mgruner** [comment]
That is a warning from newer Perl versions. You should always dereference hash references before calling ```keys``` on them. ```keys $Hash``` -> ```keys %{ $Hash }```.

**Comment by thorsteneckel** [comment]
Hi there! We have a CodePolicy rule for that. Any interest in a contribution?

**Comment by s7design** [comment]
Hi all,

Yes I saw that, I changed a little bit that. Please let me know what do you think about current version, to be honest I prefer case which Martin suggested if you would like I will be able to update the tests again.

Regards
Zoran

**Comment by mgruner** [comment]
Hi @thorsteneckel, to make it work on older Perls too? I would like to take a look, yes.

**Comment by thorsteneckel** [comment]
Hi @mgruner - No. We basically check for the "... keys $..." pattern and report it as an error. We discussed an "automatic fix" solution but decided to go with an error to sensitize us developers. If you are interested I can prepare a pull request to avoid this old/new Perl issues via the OTRSCodePolicy.

**Comment by zottto** [comment]
Hi @s7design,
I'm sorry that I still can't merge your PR, but the Selenium tests are failing on my system.

```
Example:
bin/otrs.Console.pl Dev::UnitTest::Run --test Selenium/Agent/Admin/AdminQueueTemplates
+-------------------------------------------------------------------+
/ws/otrs/otrs-head//scripts/test/Selenium/Agent/Admin/AdminQueueTemplates.t:
+-------------------------------------------------------------------+
.................................................................... not ok 69 - 'No data matches' is displayed'
............... not ok 85 - queuetest14578286710 is not in a relation with standard templatetest14578286721 (is '1' should be '0')
.......
=====================================================================
 Product:     OTRS 6.0.x git
 Test Time:   33 s
 Time:        2016-03-13 01:24:50
 Host:        vm-entwicklung
 Perl:        5.18.2
 OS:          Linux
 Vendor:      ubuntu 14.04
 Database:    mysql 5.5.38
 TestOk:      90
 TestNotOk:   2
 FailedTests:
  /ws/otrs/otrs-head//scripts/test/Selenium/Agent/Admin/AdminQueueTemplates.t #69 - 'No data matches' is displayed', 85 - queuetest14578286710 is not in a relation with standard templatetest14578286721
=====================================================================
```

Can you please double check that the tests are running on your systems? Especially, for all Selenium tests file you updated, I get failing tests on "No data matches is displayed".

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

I updated PR, there is one potential problem and I added a sleep for filter. In Vanilla system it is not necessary, but if there are many entities for some filters search could take some time and in that case test will fail.

Please let me know if it works now, because in my system it had worked before as well.

Regards
Zoran

**Comment by zottto** [comment]
Merged with c39383b (master) and 2a84fd7 (OTRS 5). Thanks!

**Pull request closed without merging**
