### PR TITLE
Master - JS refactoring - AdminProcessManagementPath

### PR DESCRIPTION
**Pull request by s7design**
Hello @zottto ,

Hereby is refactored AdminProcessManagementPath JS. Consider this PR after we resolve PR ( #1271 ), since there will be some merge conflicts and i will rebase this branch once we merge it.

Please let me know if you have any issues or comments regarding this PR.

Regards,
Sanjin

### CODE REVIEW

**Comment by zottto** [comment]
Hi Sanjin / @s7design,

if you name the config vars in the AddJSData() call correctly, you don't have to set them in the JS file again. Please use the correct config names used in the JS file directly in teh AddJSData() call.

Thanks,
Marc

**Comment by s7design** [comment]
Hello @zottto ,

Thank you for follow up, PR is rebased and updated.

Regards,
Sanjin

**Comment by zottto** [comment]
Hi Sanjin / @s7design,

thanks for the rebase. Is there a reason, why the call for InitPathEdit() is delayed for a second?

Thanks,
Marc

**Comment by s7design** [comment]
Hi @zottto 

I am working on this, in my opinion it doesn't work properly. I think this delay is not necessary, there we should find another approach.  

Regards
Zoran

**Comment by s7design** [comment]
Hi @zottto 

I updated thi PR, and I hope I fxed it. After testing long time, I saw there is a problem if JS data is named "Config.SomeName". I renamed these data, actually I removed Config and there are the following ones:
- TransitionEntityID 
- ProcessEntityID 
- StartActivityID

 As I mentioned in the previous comment delay of 1 second was wrong idea. In that case there was not logged JS error but there also were not loaded right data on the screen.
Now  AdminProcessManagementPath  screen works fine. Please let me know what do you think about that.

Regards
Zoran

**Comment by zottto** [comment]
Merged with e9f7580.

Thanks,
Marc

**Pull request closed without merging**
