### PR TITLE
[ Master - bug6350 ] -  Sort order in Auto Responses <-> Queues

### PR DESCRIPTION
**Pull request by s7design**
http://bugs.otrs.org/show_bug.cgi?id=6350

### CODE REVIEW

**Comment by s7design** [comment]
Hi @mgruner and @mrcbnsls 

When we worked with AutoResponse the previous days we had seen that there is this bug report. We also thought that it could be useful if there were such filter. Because of that we made this PR with our proposal.

If you thin that it is good solution you can merge it in master. If you have any suggestion please let me know.

Regards
Zoran

**Comment by carlosgarciac** [comment]
Hi @s7design,

The proposal is nice for me, but the fact to enable it using a sysconfig setting is disabled by default is not the best option IMO, due it will be hidden for users and only if they realize about the config it will be shown. Could you please perform next changes?:

1.- Remove the Sysconfig entry and include the button directly on the screen.
2.- If possible please add a short hint (FieldExplanation) about this functionality, "This filter allow you to ..."
3.- For SQL statement style on "Kerne/System/Autoresponse.pm" please fit it with examples on "Kernel/System/Ticket.pm" TicketGet method.
 
Any comment about this changes is so welcome, thanks in advance for your nice effort.


Best regards,
Carlos García

**Comment by s7design** [comment]
Hi @carlosgarciac 

At first, I rebased this PR because there have been many changes in meantime. Now I will update with your suggestions. It will be done soon.

Regards
Zoran

**Comment by s7design** [comment]
Hi @carlosgarciac,

I updated PR with your suggestion. I am not sure if I understand you regarding to:

> 3.- For SQL statement style on "Kerne/System/Autoresponse.pm" please fit it with examples on "Kernel/System/Ticket.pm" TicketGet method.

I changed SQL style a little bit, but please check if I have done it well. I also add title for the buttons which display hint on hover. Real FieldExplanation class is not good for this case, I believe it is better now.

Please let me know if you have any suggestion.

Regards
Zoran

**Comment by carlosgarciac** [comment]
Hi @s7design,

Zoran sorry for the delay, changes looks fine for me, could you please rebase?, then I will to merge these changes, thanks in advance for your help.

Best regards,
Carlos García

**Comment by s7design** [comment]
Hi Carlos,

I rebased this PR and changed test a little bit. I hope it is good now. 

Regards
Zoran

**Comment by carlosgarciac** [comment]
Hi @s7design,

your PR was merged in f276926, thanks a lot for your effort.

Best regards,
Carlos García

**Pull request closed without merging**
