### PR TITLE
Add graceful restart support && Limit on requests per one process

### PR DESCRIPTION
**Pull request by dnikolayev**
Because of the size of the project OTRS may have memory leaks.
When you run it on FastCGI, you get up to 1GB processes in memory in 1-2 days on active environments. So, if you get like 100-1000 requests, then graceful exit/restart by your FastCGI manager (like multiwatch) - the problem is solved.

Also, it is not useful to do restarts on some changes in SysConfig or ProcessManagemnt on FastCGI. As you don't see your changes after saving and need to restart processes manually after updating them. It is easy to make a graceful exit (with finishing all active requests gracefully) by a signal from FS watcher on ZZZAuto.pm, ZZZAAuto.pm and ZZZProcessManagement.pm

### CODE REVIEW

**Comment by dnikolayev** [comment]
Closing this pull request, probably it is better to do in special dir with all examples

**Comment by dnikolayev** [comment]
Placed all changed needed to run OTRS into new directory bin/nginx_fcgi-bin
Also, included all examples needed to run it on: Nginx + supervisor + spawn_fcgi + multiwatch
Moved out Mecached Cache module to another branch to not influence on this pull request, as it I didnt apply all OTRS style fully yet to it

**Comment by mgruner** [comment]
Hello @dnikolayev. First of all, impressive, thanks a lot for your suggestion! May I ask you to sign our CLA as described on https://otrs.github.io for future contributions please?

Regarding the PR at hand, I would not want to merge it at this point. It has a lot of code to solve a simple problem and doesn't follow our coding standards. You could use http://search.cpan.org/~alexmv/Module-Refresh-0.17/lib/Module/Refresh.pm to solve the refreshing problem. And then perhaps a simple counter on fcgi-bin/*.pl would do.

Please reconsider this. I'm absolutely open for improvements on our fcgi handlers, but I cannot merge the PR at hand.

Best regards, Martin

**Comment by mgruner** [comment]
Module::Refresh is acutally already bundled with OTRS and used by app.psgi.

**Comment by dnikolayev** [comment]
Ok, thnx, Martin
When we made implementation - it was not accessible.. 
What about Memcached/Redis modules, can we release it, or it is not ok according to business version? A lot of people would be happy because of it?

**Comment by mgruner** [comment]
Hello @dnikolayev. We do have an OTRS Business Solution™ feature for Memcached caching that we would not like to release publicly at this point. Redis is not available yet, but would likely become such a feature as well. You are definitely free to release these modules to the public yourself.

If you are interested in a code review, you can send the modules to manuel.hecht@otrs.com (@ManuelHecht). We will respect your copyright and not use the code unless you give us permission to do so. 

Best regards, Martin

**Pull request closed without merging**
