### PR TITLE
Add support for X-OTRS-Title in PostMaster/NewTicket

### PR DESCRIPTION
**Pull request by reneeb**
This can be helpful when a postmaster filter wants to change/set the ticket title based on some calculations/checks...

### CODE REVIEW

**Comment by mgruner** [comment]
Hello @reneeb. Thanks for the suggestion! It seems however, that `X-OTRS-Title` is not supported anywhere else (for example in FollowUp.pm) so this would be an inconsistent addition. Additionally it would be good to cover this with unit tests as well. What do you think?

**Comment by reneeb** [comment]
If you're interested, I would add the Header in other packages as well and add unittests

**Comment by mgruner** [comment]
@reneeb please do so. If we have a consistent state we can merge this.

**Comment by mgruner** [comment]
@reneeb, when do you think you will be able to work on this?

**Comment by reneeb** [comment]
next week...

**Comment by reneeb** [comment]
Improved version is available: #1127

**Pull request closed without merging**
