### PR TITLE
Added ExtFQDN option, parameter name fixed, internal data removed from some Message-IDs

### PR DESCRIPTION
**Pull request by pboguslawski**
OTRS uses the fully qualified domain name (FQDN SysConfig setting)
for external IDs generation (i.e. Message-ID in e-mail messages,
ContentID for pasted images). If OTRS instance uses internal
domain for FQDN, this internal domain name will leak to third
parties in e-mail message headers which may be not desirable.

This mod introduces new SysConfig option ExtFQDN which allowes
one to define the fully qualified domain name for external IDs
generation (i.e. Message-ID in e-mail messages, Content-ID for
pasted images).

It also fixes parameter name in Bounce() call and removes UserID
and TicketID from some Message-IDs generated by OTRS (this
is internal data and it's not necessary to expose it to third
parties in e-mail message headers).

Related: https://dev.ib.pl/ib/otrs/issues/40
Related: http://bugs.otrs.org/show_bug.cgi?id=9003
Author-Change-Id: IB#1009570

### CODE REVIEW

**Comment by pboguslawski** [comment]
Hi,

In case you still don't want this mod in your sources (http://bugs.otrs.org/show_bug.cgi?id=9003) consider merging only parameter name fix in Bounce() call and removing ticketid and userid from Message-ID.

Regards,
Pawel

**Comment by jensoliver** [comment]
Looks OK for me

**Comment by mgruner** [comment]
Hello @pboguslawski, thanks a lot for your pull request. As we already discussed in the linked bug 9003, I don't see an important use case for the framework yet. I have improved the ArticleBounce() method as suggested in 690d39648c14a776bb7a7fdc4ee0fc97dff63d6a.
Best regards, Martin

**Comment by pboguslawski** [comment]
Thank you. Please note that 3103142c75d6cc7987581e2949e22bfafd694691 does not contain ArticleBounce() fix and there is another one place to remove ticketid and userid from MessageID in our PR.

Regards,
Pawel

**Comment by mgruner** [comment]
What do you mean by "does not contain"? I don't understand. What is missing?

**Comment by pboguslawski** [comment]
> What do you mean by "does not contain"? 

You wrote

> I have improved the ArticleBounce() method as suggested in 690d396

but there is no such change in code in  690d396 nor 3103142.

Consider removing ticketid and userid also in

https://github.com/OTRS/otrs/blob/master/Kernel/System/Ticket/Article.pm#L2240

Regards,
Pawel

**Comment by mgruner** [comment]
I removed the TicketID and UserID in ArticleBounce as you suggested. Now also for ArticleCreate in 686ac7fb6425228b7a83f7b5088b1c207425a5a5. Please let me know if there is anything wrong.

**Comment by pboguslawski** [comment]
ticketid and userid removal looks ok now.

One more fix left (see our PR - there is parameter name mismatch in Bounce() call:

    -        MessageID => $NewMessageID,
    +        'Message-ID' => $NewMessageID,

Regards,
Pawel

**Comment by mgruner** [comment]
Thanks, fix applied in 4f0cbb02bc2192cf1a6d9637fdbdb61ab944ad8b.

**Pull request closed without merging**
