### PR TITLE
Fixed security issue

### PR DESCRIPTION
**Pull request by rolfschmidt**
http://forums.otterhub.org/viewtopic.php?f=62&t=35249&p=142506

https://znuny.com/en/#!/advisory/ZSA-2017-01

### CODE REVIEW

**Comment by mgruner** [comment]
Hi @rolfschmidt. Thanks, similar fix applied in all relevant branches. And thanks for not fully disclosing this. We'll release very soon.

**Comment by urbalazs** [comment]
> We'll release very soon.
@mgruner can you sync the modified strings to Transifex? I would like to complete the missing translation before release.

**Comment by mgruner** [comment]
@urbalazs: just pushed. You have to hurry though, @carlosfrodriguez will build soon. @carlosfrodriguez, can you please pull the translations right before the build?

**Comment by carlosfrodriguez** [comment]
Hi @mgruner, @urbalazs 

For sure I will leave OTRS 5 at the end to give @urbalazs time to work on translations.

**Comment by urbalazs** [comment]
@mgruner @carlosfrodriguez 
Translation is done! Thanks!

**Pull request closed without merging**
