### PR TITLE
contribute CustomerCompany/Add.pm (most code borrowed from CustomerUs…

### PR DESCRIPTION
**Pull request by babafou**
…er/Add.pm)

### CODE REVIEW

**Comment by mgruner** [comment]
Hello @babafou, could you please sign the OTRS CLA as described on https://otrs.github.io?

**Comment by babafou** [comment]
Martin Gruner <notifications@github.com> écrit :
> Hello @babafou, could you please sign the OTRS CLA as described on https://otrs.github.io?

OK, sent to cla@otrs.com.

**Comment by mgruner** [comment]
CLA received, thanks!

**Comment by mgruner** [comment]
Merged in 584d9e5 for OTRS 5. Thanks a lot :+1:! I applied small naming changes to the parameter names and added a unit test. Regards, Martin

**Pull request closed without merging**
